### ISSUE TITLE
Java: property getter implementations (e.g: from an interface) may be ignored

### ISSUE THREAD

**Issue by skinny85** [aws/jsii#1005]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** `0.20.6`
* **Platform:**     Darwin 186590cdb71d.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### What is the problem?

I think there is a problem when implementing an interface from Java that has a property (not method) on the TypeScript side. This can be seen with CodePipeline actions:

```ts
export interface IAction {
  readonly actionProperties: ActionProperties;

  bind(scope: Construct, stage: IStage, options: ActionBindOptions): ActionConfig;

  onStateChange(name: string, target?: events.IRuleTarget, options?: events.RuleProps): events.Rule;
}
```

When trying to implement it like so:

```java
public class MyCodePipelineAction implements IAction {
    @Override
    public ActionProperties getActionProperties() {
        return ActionProperties.builder()
                .actionName("MyAction")
                .artifactBounds(ActionArtifactBounds.builder()
                        .minInputs(0)
                        .maxInputs(0)
                        .minOutputs(0)
                        .maxOutputs(0)
                        .build()
                )
                .category(ActionCategory.BUILD)
                .provider("random")
                .build();
    }

    // ...
}
```

you get the following error:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project callbacks: An exception occured while executing the Java class. Only root constructs may have an empty name
[ERROR] Error: Only root constructs may have an empty name
[ERROR]     at new ConstructNode (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/core/lib/construct.js:29:23)
[ERROR]     at new Construct (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/core/lib/construct.js:435:21)
[ERROR]     at Stage.attachActionToPipeline (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:104:29)
[ERROR]     at Stage.addAction (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:64:33)
[ERROR]     at new Stage (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:25:18)
[ERROR]     at Pipeline.addStage (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:160:23)
[ERROR]     at new Pipeline (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-sgkAMx/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:129:18)
[ERROR]     at obj._wrapSandboxCode (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7741:49)
[ERROR]     at Kernel._wrapSandboxCode (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:8197:19)
[ERROR]     at Kernel._create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7741:26)
[ERROR]     at Kernel.create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7495:21)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7285:28)
[ERROR]     at KernelHost.run (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7225:14)
[ERROR]     at Immediate.setImmediate [as _onImmediate] (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime1520872413187170626/jsii-runtime.js:7228:37)
[ERROR]     at runCallback (timers.js:705:18)
[ERROR]     at tryOnImmediate (timers.js:676:5)
[ERROR]     at processImmediate (timers.js:658:5)
```

which I believe corresponds to [this code](https://github.com/aws/aws-cdk/blob/2d92ab3e22130408056257d87620a3e03d75b226/packages/%40aws-cdk/aws-codepipeline/lib/stage.ts#L135-L135) in the CodePipeline construct.

Interestingly, if you remove the `.actionName("MyAction")` line, some non-null validation kicks in, and you get:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project callbacks: An exception occured while executing the Java class. java.lang.NullPointerException: actionName is required
[ERROR] Error: java.lang.NullPointerException: actionName is required
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5132539127564955369/jsii-runtime.js:7250:27)
[ERROR]     at KernelHost.callbackHandler (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5132539127564955369/jsii-runtime.js:7239:33)
[ERROR]     at Object.get [as actionProperties] (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5132539127564955369/jsii-runtime.js:7828:37)
[ERROR]     at Stage.addAction (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-oGVaTw/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:57:35)
[ERROR]     at new Stage (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-oGVaTw/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:25:18)
```

### Impact to CDK
* When implementing abstract properties’ getters, the implementation may not be correctly used by the Java runtime. This can cause some of the desired properties to be missing in the synthesized CloudFormation template.
* _Workaround_: there is no known workaround for this issue.

**Comment by skinny85** [comment]
Still does not work with CDK `1.17.0` and JSII `0.20.7`:


```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project callbacks: An exception occured while executing the Java class. com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `software.amazon.awscdk.services.codepipeline.IStage` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1]
[ERROR] Error: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `software.amazon.awscdk.services.codepipeline.IStage` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1]
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7258:27)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7335:16)
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7266:25)
[ERROR]     at KernelHost.callbackHandler (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7247:33)
[ERROR]     at Object.value (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7920:41)
[ERROR]     at Pipeline._attachActionToPipeline (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-NcEZYG/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:199:41)
[ERROR]     at Stage.attachActionToPipeline (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-NcEZYG/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:105:31)
[ERROR]     at Stage.addAction (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-NcEZYG/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:64:33)
[ERROR]     at new Stage (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-NcEZYG/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:25:18)
[ERROR]     at Kernel._wrapSandboxCode (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:8205:19)
[ERROR]     at Kernel._create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7749:26)
[ERROR]     at Kernel.create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7503:21)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7293:28)
[ERROR]     at KernelHost.run (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7233:14)
[ERROR]     at Immediate.setImmediate [as _onImmediate] (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime7871481349219937575/jsii-runtime.js:7236:37)
[ERROR]     at runCallback (timers.js:705:18)
[ERROR]     at tryOnImmediate (timers.js:676:5)
[ERROR]     at processImmediate (timers.js:658:5)
```

Repro: https://github.com/rix0rrr/jsii-test-drive/blob/abe47e9cbbb5cb61c738bb073190da497fcc0905/java/callbacks/src/main/java/com/myorg/HelloStack.java#L84

**Comment by skinny85** [comment]
New location of the repro: https://github.com/rix0rrr/jsii-test-drive/blob/9cefddb2b3bfb0b3aa7184bd41c4355c062ca55d/java/interface-property/src/main/java/com/myorg/HelloStack.java#L54-L54
