### ISSUE TITLE
.net: aspect application fails at cdk's synth time

### ISSUE THREAD

**Issue by nija-at** [aws/jsii#1028]
## :bug: Bug Report

Synthesizing app - https://github.com/rix0rrr/jsii-test-drive/blob/c1e6fbf986e3a64266bbba634fe82059982920fe/dotnet/serverless/src/Serverless/Program.cs - fails with the following error - 

```bash
Unhandled exception. System.ArgumentException: Could not convert argument 'Serverless.Node12Aspect' to Jsii (Parameter 'arguments')
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceVoidMethod(Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.ConstructNode.ApplyAspect(IAspect aspect)
   at Serverless.Program.Main(String[] args) in /Users/nija/workplace/cdk/jsii-test-drive/dotnet/serverless/src/Serverless/Program.cs:line 50
Subprocess exited with error 134
```

The error is due to application of the `Node12Aspect`.

**Comment by RomainMuller** [comment]
`Node12Aspect` needs to extend `DeputyBase` (this is a defect tracked at #1029), I reckon this is what's missing.
