### ISSUE TITLE
Java: Implementing or overriding overloaded methods in Java does not work consistently

### ISSUE THREAD

**Issue by skinny85** [aws/jsii#1034]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** `0.20.7`
* **Platform:**   Darwin 186590cdb71d.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### What is the problem?

This code works in TypeScript:

```ts
import { Construct, Stack } from '@aws-cdk/core';
import events = require('@aws-cdk/aws-events');

export class MyStack extends Stack {
    constructor(scope: Construct, id: string) {
        super(scope, id);

        new events.Rule(this, 'Rule', {
            targets: [
                new MyTarget(),
            ],
            eventPattern: {
                source: ['my-source'],
            },
        });
    }
}

class MyTarget implements events.IRuleTarget {
    public bind(rule: events.IRule, id?: string): events.RuleTargetConfig {
        if (!id) {
            throw new Error("Expected 'id' to be passed!");
        }
        return {
            arn: 'arn',
            id: '',
        };
    }
}
```

But the following does not in Java:

```java
public class HelloStack extends Stack {
    public HelloStack(final Construct parent, final String id) {
        this(parent, id, null);
    }

    public HelloStack(final Construct parent, final String id, final StackProps props) {
        super(parent, id, props);

        // tests a callback getting an optional parameter be non-null
        Rule.Builder.create(this, "Rule")
                .targets(asList(new MyEventTarget()))
                .eventPattern(EventPattern.builder()
                        .source(asList("source"))
                        .build()
                )
                .build();
    }
}

class MyEventTarget implements IRuleTarget {
    @Override
    public RuleTargetConfig bind(IRule rule) {
        throw new RuntimeException("Expected bind(IRule, String) to be called!");
    }

    @Override
    public RuleTargetConfig bind(IRule rule, String id) {
        if (id == null) {
            throw new RuntimeException("Expected id to be not null!");
        }
        return RuleTargetConfig.builder()
                .arn("arn")
                .id(id)
                .build();
    }
}
```

Full repro: https://github.com/rix0rrr/jsii-test-drive/tree/master/java/callback-optional-provided

### Verbose Log

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project callback-optional-provided: An exception occured while executing the Java class. java.lang.RuntimeException: Expected bind(IRule, String) to be called!
[ERROR] Error: java.lang.RuntimeException: Expected bind(IRule, String) to be called!
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7258:27)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7335:16)
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7266:25)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7335:16)
[ERROR]     at KernelHost.completeCallback (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7266:25)
[ERROR]     at KernelHost.callbackHandler (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7247:33)
[ERROR]     at Object.value (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7920:41)
[ERROR]     at Rule.addTarget (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-2JalbH/node_modules/@aws-cdk/aws-events/lib/rule.js:68:36)
[ERROR]     at new Rule (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-kernel-2JalbH/node_modules/@aws-cdk/aws-events/lib/rule.js:42:18)
[ERROR]     at Kernel._wrapSandboxCode (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:8205:19)
[ERROR]     at Kernel._create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7749:26)
[ERROR]     at Kernel.create (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7503:21)
[ERROR]     at KernelHost.processRequest (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7293:28)
[ERROR]     at KernelHost.run (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7233:14)
[ERROR]     at Immediate.setImmediate [as _onImmediate] (/private/var/folders/gl/mhgz0kz11lqgc0dklyry83xnyfk1zw/T/jsii-java-runtime5443972052528047576/jsii-runtime.js:7236:37)
[ERROR]     at runCallback (timers.js:705:18)
[ERROR]     at tryOnImmediate (timers.js:676:5)
[ERROR]     at processImmediate (timers.js:658:5)
```

### Impact to CDK
* Methods with optional parameters in the construct library are represented in Java by a series of overloads (the method with all the parameters, and overloads without optional arguments).
* When implementing multiple overloaded methods, the runtime binds only one of the implementations (which one is non-deterministic), which may result in incorrect behavior.
* _Workaround_: when overriding methods, only override the variant with all the parameters. There is no known way to work around this problem when implementing CDK interfaces.

**Comment by RomainMuller** [comment]
The reason is because there can be only one callback for a given name, and the interface generates an overload. The way callbacks get processed means that only one of them (which one may be non-deterministic) may ever be invoked by the callback handler.

**Comment by skinny85** [comment]
> *Workaround*: when overriding methods, only override the variant with all the parameters. There is no known way to work around this problem when implementing CDK interfaces.

This isn't really a workaround, though, is it (it doesn't work in the repro example, for one thing)?
