### ISSUE TITLE
Cryptic error when `author` in package.json is a string

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1148]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.20.11 (build d4fd44f), typescript 3.7.4
* **Platform:**    Darwin 8c859031ce16.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

### What is the problem?

Repro:

```shell
$ mkdir foo && cdk foo
$ npm init -y
$ yarn add -D jsii
$ jsii
Error: Error: Invalid stringified "person" value:
    at Object.parsePerson (/Users/benisrae/playground/jsii-watch-issue/node_modules/jsii/lib/utils.js:64:15)
    at _toPerson (/Users/benisrae/playground/jsii-watch-issue/node_modules/jsii/lib/project-info.js:164:25)
    at Object.loadProjectInfo (/Users/benisrae/playground/jsii-watch-issue/node_modules/jsii/lib/project-info.js:74:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by netroy** [comment]
@eladb looks like author field being a string is not the issue. 
This happens only when the author field is an empty string.

The [`_required`](https://github.com/aws/jsii/blob/master/packages/jsii/lib/project-info.ts#L121) check here should probably treat an empty string just the same as it treats a null, or a missing field.

**Comment by RomainMuller** [comment]
@netroy - thanks for looking into that. It makes total sense... And clarifies the route for improving the situation!

**Comment by netroy** [comment]
@RomainMuller if you have a preference for how this should be fixed, I can send a PR.

**Comment by RomainMuller** [comment]
I guess in this context empty string should behave the same as `undefined` (aka missing).
