### ISSUE TITLE
 `long_description` has syntax errors in markup and would not be rendered on PyPI when 'npm run package'

### ISSUE THREAD

**Issue by mbonig** [aws/jsii#1244]
### Affected Languages
- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 6.13.6
* **Platform:**      4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What is the problem?
When attempting to Package a JSII module I get the following error:

```
> jsii-pacmak

Error: Process exited with status 1
Checking /mnt/c/Users/xxxx/secure-bucket/dist/python/mbonig.secure_bucket-1.0.0-py3-none-any.whl: FAILED          `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 11: Warning: Inline literal start-string without end-string.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
```

### Verbose Log

```
> jsii-pacmak "--verbose"

[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'python' for secure-bucket
[jsii-pacmak] [INFO] Packaging 'java' for secure-bucket
[jsii-pacmak] [INFO] Packaging 'dotnet' for secure-bucket
[jsii-pacmak] [INFO] Packaging 'js' for secure-bucket
[jsii-pacmak] [INFO] js finished
Error: Process exited with status 1
Checking /mnt/c/Users/xxx/secure-bucket/dist/python/mbonig.secure_bucket-1.0.0-py3-none-any.whl: FAILED          `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 11: Warning: Inline literal start-string without end-string.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Checking /mnt/c/Users/mboni/projects/secure-bucket/dist/python/mbonig.secure-bucket-1.0.0.tar.gz: PASSED


    at ChildProcess.<anonymous> (/mnt/c/Users/mboni/projects/secure-bucket/node_modules/jsii-pacmak/lib/util.js:57:31)        at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by mbonig** [comment]
I should add... looking through code I suspected it might be an issue with my README.md file, but even if I remove all content and have a blank file, I still get the error.

**Comment by MrArnoldPalmer** [comment]
@mbonig Thanks for the report.

You have your current jsii version as `6.13.6` which doesn't exist. Assuming you're experiencing this on the current release, `0.22.0`. Is that correct?

**Comment by mbonig** [comment]
Actually, 0.21.2, must have misread the jsii-verbose output. Reference here:

https://github.com/mbonig/secure-bucket/blob/master/package.json

Oddly enough this doesn't appear to happen during my Github Actions...

https://github.com/mbonig/secure-bucket/runs/432217140?check_suite_focus=true

**Comment by MrArnoldPalmer** [comment]
Yeah something is funny here. Might be a Windows specific issue. Will dig in a bit more.

**Comment by richardhboyd** [comment]
I'm seeing this on Amazon Linux as well. I suspect that the [`setup.py`](https://github.com/aws/jsii/blob/7dd04fe9987bbba7b1360162b7afc2caf15a50e6/packages/%40jsii/python-runtime/setup.py#L9) file generated by JSII is referencing a README.md file that doesn't exist.

If I follow the directions in the jsii README for a sample project, it works correctly if I have uninstalled twine. I can then attempt to `pip install /path/to/project/dist/python/such_and_such.tgz` and it fails with the `long_description` error @mbonig described. installing twine and attempting to re-run `npm run package` generates the same error.

**Comment by richardhboyd** [comment]
disregard. I'm a big 'ole dummy.

## Old and busted
````bash
pip install ../jsii-test/dist/python/acme.hello-jsii-1.0.0.tar.gz --user
````

## New hotness
````bash
pip install --no-index --find-links=../jsii-test/dist/python acme.hello_jsii
````

**Comment by MrArnoldPalmer** [comment]
oooh interesting. I wonder if a similar fix can be found for @mbonig's issue. I've always relied on the `old and busted` for referencing local packages.

@mbonig if you clean your project repo does `jsii-pacmak` fail with the error at first run, or is it only after running `pip install` on the package following a first successful build?

**Comment by mbonig** [comment]
Just updated to latest versions of everything and I don't get the error anymore.

**Comment by gradybarrett** [comment]
jsii@1.61.0
projen@0.58.15
building on [atlassian-bamboo-elastic-image@6.12](https://packages.atlassian.com/maven/repository/public/com/atlassian/bamboo/atlassian-bamboo-elastic-image/6.12/)

Just ran into this today. Were there any other solutions to this?

My project was set up using a projen 0.58.15 JsiiProject, which is running `jsii-pacmak -v --target python` in CI. It only happens in CI for me, and only the wheel fails the twine check. Locally I can package and twine check passes for both the wheel and tar.

I notice pacmak runs twine check using a python in /opt/tmp/npm-pack<randomchars>/.env-<randomchars>/bin/python. I haven't dug through JSII code to understand which python that is. The agents we use have pyenv and I'm doing build tool updates prior to package. So I'm wondering if that referenced python version isn't what I think it is...
