### ISSUE TITLE
jsii-pacmak@1.0.0 fails to build maven target

### ISSUE THREAD

**Issue by jsdtaylor** [aws/jsii#1295]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.0.0 (build eb2db9d), typescript 3.7.5
* **Platform:**    Darwin Elegant-Development-2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### What is the problem?
`jsii-pacmak` (1.0.0) fails for maven targets with a `Could not resolve version conflict among [...]` error.

### Verbose Log
```sh
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'python' for aws-cdk-dynamodb-seeder
[jsii-pacmak] [INFO] Packaging 'dotnet' for aws-cdk-dynamodb-seeder
[jsii-pacmak] [INFO] Packaging 'java' for aws-cdk-dynamodb-seeder
[jsii-pacmak] [INFO] Packaging 'js' for aws-cdk-dynamodb-seeder
[jsii-pacmak] [INFO] js finished
[jsii-pacmak] [WARN] Exception occurred, not cleaning up /var/folders/vh/1p1_c0fx3dj9hhdh1nd8wkd40000gn/T/npm-packsFd1bj
Error: Process exited with status 1
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder                   [jar]
[INFO] aggregatepom                                                       [pom]
[INFO] 
[INFO] ----------< uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder >----------
[INFO] Building uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder 1.3.3    [1/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder 1.3.3 FAILURE [  0.412 s]
[INFO] aggregatepom 1.0.0 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.494 s
[INFO] Finished at: 2020-02-26T17:30:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aws-cdk-dynamodb-seeder: Could not resolve dependencies for project uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Failed to collect dependencies for uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Could not resolve version conflict among [software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-common:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudformation:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudwatch:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-region-info:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ssm:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:events:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:logs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sqs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cdk-cx-api:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:kms:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:core:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sns:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sns-subscriptions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancing:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancingv2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:apigateway:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:servicediscovery:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.jsii:jsii-runtime:jar:[1.0.0,2.0.0)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


    at ChildProcess.<anonymous> (/Users/jtaylor/Code/src/github.com/elegantdevelopment/aws-cdk-dynamodb-seeder/node_modules/jsii-pacmak/lib/util.js:57:31)
    at Object.onceWrapper (events.js:313:26)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

**Comment by MrArnoldPalmer** [comment]
hey @jsdtaylor, you mind pasting your package.json?

FYI the current version of the cdk packages (1.26.0) is still on jsii@0.22.0. If you're depending on any of those packages this could be causing the version mismatch.

**Comment by jsdtaylor** [comment]
@MrArnoldPalmer yep, here y'go: https://github.com/elegantdevelopment/aws-cdk-dynamodb-seeder/blob/v1.3.3/package.json

**Comment by jsdtaylor** [comment]
Ok, so... I got further with jsii@0.22.0, but had a load of compilation errors. It was the package name that was causing that issue, due it being kebab-cased (I think the JSON config section of the documentation could do with some enhancement).

But otherwise, it's all good! Should we keep this open for the original issue or close it as jsii@1.0.0 isn't supported by any version of CDK yet (in the context of this issue)?

**Comment by MrArnoldPalmer** [comment]
@jsdtaylor So once you fixed the version mismatch, did the compilation error clearly indicate that the artifact id needed to be changed? That is something that we could fix.

We have a tool `jsii-config` that helps users automatically setup the package.json `jsii` config, we could add some validation there that makes sure the java artifact id is formatted correctly, in addition to more strict validation when running `jsii`.

Closing in favor of https://github.com/aws/jsii/issues/1299

**Comment by jsdtaylor** [comment]
@MrArnoldPalmer yes, with 0.22.0 this was precisely the case. However, this issue still affects jsii-pacmak 1.0.0, even with the package name cased correctly.

**Comment by mbonig** [comment]
Agreed. I see this error too when building a recent construct. I don't think it's a casing/naming issue:

```
"jsii": {
    "outdir": "dist",
    "targets": {
      "python": {
        "distName": "mbonig.cicd-spa-website",
        "module": "mbonig.cicd-spa-website"
      },
      "java": {
        "package": "com.mbonig.cicaspawebsite",
        "maven": {
          "groupId": "com.mbonig",
          "artifactId": "cicdspawebsite"
        }
      },
      "dotnet": {
        "namespace": "MBonig.CicdSpaWebsite",
        "packageId": "MBonig.CicdSpaWebsite"
      }
    }
  }
  
```

Fails with messages like:

```
Could not resolve version conflict among [software.amazon.awscdk:certificatemanager:jar:[1.27.0,2.0.0) -> software.amazon.awscdk:cloudformation:jar:[1.27.0,1.27.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0) ....
```

**Comment by MrArnoldPalmer** [comment]
@mbonig `aws-cdk` v1.27.0 still relies on jsii `v0.22.0`, so you will need to build your constructs with that for the time being. Next release of jsii + cdk should fix that.
