### ISSUE TITLE
IDictionary doesn't work with Fsharp dictionary implementation

### ISSUE THREAD

**Issue by Lanayx** [aws/jsii#1322]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [X] .NET (F#)

### General Information
* **JSII Version:** 0.22.0
* **Platform:**     Windows 10 

### What is the problem?

Properties whose type is IDictionary (for example **Environment** property in different templates) can't take F# dictionary like
`Environment = dict [("alertEmails", alertEmails)]`
to make it work I have to convert it into Dictionary like 
`Environment = Dictionary(dict [("alertEmails", alertEmails)])`
which is undesirable.

The problem is that [on this line](https://github.com/aws/jsii/blob/master/packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs#L267) `valueType.GetProperty("Keys")` returns null, while if I check `((IDictionary<string, string>) value).Keys` it works.

### Verbose Log
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertMap(IReferenceMap referenceMap, TypeReference elementType, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCollection(IReferenceMap referenceMap, Object value, Boolean isOptional, CollectionTypeReference collectionType, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertClass(Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
```

**Comment by Lanayx** [comment]
This is an example of the fix for the similar issue in another library
https://github.com/Cysharp/MagicOnion/pull/207/files

**Comment by MrArnoldPalmer** [comment]
@Lanayx thanks for pointing out a possible fix. This seems relatively simple to implement.

**Comment by Lanayx** [comment]
@MrArnoldPalmer even easier fix will be to cast `value` to `IDictionary` instead of using reflection since you are trying to access properties of this interface anyway
