### ISSUE TITLE
Python: jsii-runtime.js fails with "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by alexpulver** [aws/jsii#1604]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.4.0 (installed using Python pip)
* **Platform:** Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

### What is the problem?
After switching to latest AWS CDK version (`1.34.1` at the time of this bug report), I get the below exception from `jsii` when running unit tests. This issue doesn't happen with earlier version of AWS CDK (`1.31.0` is the working version I tested).

Working example:
```bash
git clone https://github.com/alexpulver/cdk-chalice.git cdk-chalice-no-jsii-issue
cd cdk-chalice-no-jsii-issue
python3 -m venv .venv
source .venv/bin/activate
pip install pip-tools
# requirements.txt was generated using pip-tools when AWS CDK 1.31.0 was the latest version available, based on "install_requires" in setup.py
pip-sync requirements.txt requirements-dev.txt
coverage run
```

Non-working example (the difference is only newer AWS CDK version, with newer dependencies):
```bash
git clone https://github.com/alexpulver/cdk-chalice.git cdk-chalice-jsii-issue
cd cdk-chalice-jsii-issue
python3 -m venv .venv
source .venv/bin/activate
pip install pip-tools
pip-sync requirements-dev.txt 
# "pip install -e ." installs packages based on "install_requires" in setup.py, but with latest versions unlike the frozen requirements.txt above
pip install -e .
coverage run
```

### Verbose Log
```
/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:9230
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/tests/test_cdk_chalice.py", line 7, in <module>
    from aws_cdk import core as cdk
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 437, in <module>
    import aws_cdk.cloud_assembly_schema
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 11, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/cloud-assembly-schema", "1.34.1", __name__[0:-6], "cloud-assembly-schema@1.34.1.jsii.tgz")
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 215, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 330, in load
    return self._process.send(request, LoadResponse)
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 325, in _process
    process.start()
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 275, in start
    self.handshake()
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 291, in handshake
    self._next_message(), _HelloResponse
  File "/Users/apulver/Code/cdk-chalice-jsii-issue/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 261, in _next_message
    return json.loads(self._process.stdout.readline(), object_hook=ohook)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Coverage.py warning: No data was collected. (no-data-collected)
```

**Comment by MrArnoldPalmer** [comment]
Hey, what version of NodeJS are you using? Optional error bindings require Node 10 or above which is the minimum required by JSII/CDK.

**Comment by alexpulver** [comment]
That was the culprit :). I had NodeJS 9, upgrading to 10 fixed the problem - thanks!
