### ISSUE TITLE
Python: TypeError: Cannot redefine property: Symbol(__jsii__)

### ISSUE THREAD

**Issue by udondan** [aws/jsii#1983]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

Haven't tested Java and .NET yet. Those might also have this problem. The same package from NPM has no issues.

### General Information
* **JSII Version:** 1.11.0
* **Platform:**     19.6.0 Darwin Kernel Version 19.6.0

### What is the problem?
My package built with JSII, causes this error when imported in Python:

```
jsii.errors.JavaScriptError: 
  TypeError: Cannot redefine property: Symbol(__jsii__)
      at Function.defineProperty (<anonymous>)
      at Object.tagJsiiConstructor (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6488:12)
      at Kernel._addAssembly (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7899:31)
      at Kernel.load (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7669:14)
      at KernelHost.processRequest (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7456:28)
      at KernelHost.run (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7394:14)
      at Immediate._onImmediate (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7397:37)
      at processImmediate (internal/timers.js:458:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test-cdk.py", line 1, in <module>
    import cdk_iam_floyd as statement
  File "/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/__init__.py", line 494, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 239, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in load
    return self._process.send(request, LoadResponse)
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 321, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot redefine property: Symbol(__jsii__)
make: *** [test-cdk] Error 1
```

This is raised by just importing the packge:

```python
import cdk_iam_floyd as statement
```

The package in question is [cdk-iam-floyd==0.58.1](https://pypi.org/project/cdk-iam-floyd/0.58.1/). So something went wrong when building the package but I wouldn't know where to start looking.

### Verbose Log

```
> {"name":"@aws-cdk/cloud-assembly-schema","version":"1.62.0","tarball":"/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/_jsii/cloud-assembly-schema@1.62.0.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: '@aws-cdk/cloud-assembly-schema',
  version: '1.62.0',
  tarball: '/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/_jsii/cloud-assembly-schema@1.62.0.jsii.tgz',
  api: 'load'
}
[@jsii/kernel] creating jsii-kernel modules workdir: /var/folders/0k/225jvs6149jdl2d1rlhb54ym0000gp/T/jsii-kernel-Bylo8C
< {"ok":{"assembly":"@aws-cdk/cloud-assembly-schema","types":31}}
> {"name":"@aws-cdk/cx-api","version":"1.62.0","tarball":"/usr/local/lib/python3.8/site-packages/aws_cdk/cx_api/_jsii/cx-api@1.62.0.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: '@aws-cdk/cx-api',
  version: '1.62.0',
  tarball: '/usr/local/lib/python3.8/site-packages/aws_cdk/cx_api/_jsii/cx-api@1.62.0.jsii.tgz',
  api: 'load'
}
< {"ok":{"assembly":"@aws-cdk/cx-api","types":25}}
> {"name":"constructs","version":"3.0.4","tarball":"/usr/local/lib/python3.8/site-packages/constructs/_jsii/constructs@3.0.4.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: 'constructs',
  version: '3.0.4',
  tarball: '/usr/local/lib/python3.8/site-packages/constructs/_jsii/constructs@3.0.4.jsii.tgz',
  api: 'load'
}
< {"ok":{"assembly":"constructs","types":13}}
> {"name":"@aws-cdk/core","version":"1.62.0","tarball":"/usr/local/lib/python3.8/site-packages/aws_cdk/core/_jsii/core@1.62.0.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: '@aws-cdk/core',
  version: '1.62.0',
  tarball: '/usr/local/lib/python3.8/site-packages/aws_cdk/core/_jsii/core@1.62.0.jsii.tgz',
  api: 'load'
}
< {"ok":{"assembly":"@aws-cdk/core","types":161}}
> {"name":"@aws-cdk/region-info","version":"1.62.0","tarball":"/usr/local/lib/python3.8/site-packages/aws_cdk/region_info/_jsii/region-info@1.62.0.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: '@aws-cdk/region-info',
  version: '1.62.0',
  tarball: '/usr/local/lib/python3.8/site-packages/aws_cdk/region_info/_jsii/region-info@1.62.0.jsii.tgz',
  api: 'load'
}
< {"ok":{"assembly":"@aws-cdk/region-info","types":5}}
> {"name":"@aws-cdk/aws-iam","version":"1.62.0","tarball":"/usr/local/lib/python3.8/site-packages/aws_cdk/aws_iam/_jsii/aws-iam@1.62.0.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: '@aws-cdk/aws-iam',
  version: '1.62.0',
  tarball: '/usr/local/lib/python3.8/site-packages/aws_cdk/aws_iam/_jsii/aws-iam@1.62.0.jsii.tgz',
  api: 'load'
}
< {"ok":{"assembly":"@aws-cdk/aws-iam","types":78}}
> {"name":"cdk-iam-floyd","version":"0.58.1","tarball":"/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/_jsii/cdk-iam-floyd@0.58.1.jsii.tgz","api":"load"}
[@jsii/kernel] load {
  name: 'cdk-iam-floyd',
  version: '0.58.1',
  tarball: '/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/_jsii/cdk-iam-floyd@0.58.1.jsii.tgz',
  api: 'load'
}
< {"error":"Cannot redefine property: Symbol(__jsii__)","stack":"TypeError: Cannot redefine property: Symbol(__jsii__)\n    at Function.defineProperty (<anonymous>)\n    at Object.tagJsiiConstructor (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6488:12)\n    at Kernel._addAssembly (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7899:31)\n    at Kernel.load (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7669:14)\n    at KernelHost.processRequest (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7456:28)\n    at KernelHost.run (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7394:14)\n    at Immediate._onImmediate (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7397:37)\n    at processImmediate (internal/timers.js:458:21)"}
jsii.errors.JavaScriptError: 
  TypeError: Cannot redefine property: Symbol(__jsii__)
      at Function.defineProperty (<anonymous>)
      at Object.tagJsiiConstructor (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6488:12)
      at Kernel._addAssembly (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7899:31)
      at Kernel.load (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7669:14)
      at KernelHost.processRequest (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7456:28)
      at KernelHost.run (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7394:14)
      at Immediate._onImmediate (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7397:37)
      at processImmediate (internal/timers.js:458:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test-cdk.py", line 1, in <module>
    import cdk_iam_floyd as statement
  File "/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/__init__.py", line 494, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/cdk_iam_floyd/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 239, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in load
    return self._process.send(request, LoadResponse)
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 321, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot redefine property: Symbol(__jsii__)
make: *** [test-cdk] Error 1
```

**Comment by udondan** [comment]
I inspected the generated Python package. I extracted the contained tar.gz files and I'm unable to find a single occurrence of `__jsii__`. 😕

**Comment by udondan** [comment]
I have also tested this now with JSII 0.12.0, same problem.

**Comment by udondan** [comment]
I tracked this down to a single line in my package:

```typescript
export { Effect } from '@aws-cdk/aws-iam';
```

If this is the only code in your TS, this will cause the error by just importing the generated python package.

So apparently I cannot export a type from another package I have imported. Is this expected or a bug in JSII? If it is expected, then JSII should probably complain while building the package.

**Comment by RomainMuller** [comment]
Wow... So the problem here is you are re-exporting a symbol from another library, so it's effectively being assigned a second JSII FQN. This isn't something that's supposed to be allowed 😲 (I mean we could consider this as "typescript/javascript sugar" only; but right now I would have expected this to cause a compilation error).

**Comment by udondan** [comment]
Yeah I guess that the problem. It did compile without errors, and then barked when imported. If this is not supported that's perfectly fine. No need for TS only, imho 🙂
