### ISSUE TITLE
com.amazon.ask.Skill cannot be cast to com.amazon.ask.AlexaSkill

### ISSUE THREAD

**Issue by sravani-chil** [aws/jsii#2232]
```
START RequestId: 036aa13f-318f-4ab4-bfc0-b79de8a80b12 Version: $LATEST
com.amazon.ask.Skill cannot be cast to com.amazon.ask.AlexaSkill: java.lang.ClassCastException
java.lang.ClassCastException: com.amazon.ask.Skill cannot be cast to com.amazon.ask.AlexaSkill
	at com.main.HelloWorldStreamHandler.<init>(HelloWorldStreamHandler.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

END RequestId: 036aa13f-318f-4ab4-bfc0-b79de8a80b12
REPORT RequestId: 036aa13f-318f-4ab4-bfc0-b79de8a80b12	Duration: 119.34 ms	Billed Duration: 200 ms	Memory Size: 512 MB	Max Memory Used: 100 MB	Init Duration: 1132.02 ms	
com.amazon.ask.Skill cannot be cast to com.amazon.ask.AlexaSkill
java.lang.ClassCastException
```

### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 
* **Platform:**

**Comment by SomayaB** [comment]
Hi @sravani-chil, can you provide more details to help us understand the issue you encountered. Please fill in the issue template by editing the body of the issue above.
