### ISSUE TITLE
Exception is logged when Java VM is shutting down

### ISSUE THREAD

**Issue by majasb** [aws/jsii#2303]
Exception is logged when Java VM is shutting down.

### Reproduction Steps

Kotlin unit test synthesizing an empty app:
```
import software.amazon.awscdk.core.App
import kotlin.test.Test
import kotlin.test.assertEquals

class AssemblyTest {
    @Test fun testSynthesize() {
        val app = App()
        val cloudAssembly = app.synth()
        assertEquals(0, cloudAssembly.stacks.size)
    }
}
```

### What did you expect to happen?

No stacktrace logged.

### What actually happened?
```
Exception in thread "Terminate jsii client" java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:241)
	at software.amazon.jsii.JsiiRuntime.terminate(JsiiRuntime.java:224)
at java.base/java.lang.Thread.run(Thread.java:835)
```

### Environment

  - **CDK CLI Version  : 1.75.0 (build 7708242)**
  - **Framework Version: 1.75.0**
  - **Node.js Version: v12.6.0**
  - **OS               : macOS 11.0.1 (20B29)**
  - **Language (Version): Java (12.0.1)**

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
@all-contributors add @majasb for bug
