### ISSUE TITLE
bug(go): Using Aspects causes panic: Call using *awscdk.IConstruct as type awscdk.IConstruct

### ISSUE THREAD

**Issue by corymhall** [aws/jsii#2793]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [X] `Go`

### General Information
* **JSII Version: v1.28.0** 
* **Platform:  18.04.1-Ubuntu**     

### What is the problem?

I am trying to use Aspects with the go CDK and I get the below error when running synth:

```
panic: reflect: Call using *awscdk.IConstruct as type awscdk.IConstruct

goroutine 1 [running]:
github.com/aws/jsii-runtime-go.Invoke(0x6e8de0, 0xc00009a270, 0x70535b, 0x5, 0xc0002a7ec8, 0x1, 0x1, 0x6900c0, 0xc0000a68a0)
        /home/ubuntu/environment/cdk/cdk-project-go/vendor/github.com/aws/jsii-runtime-go/runtime.go:216 +0x2b7
github.com/aws/aws-cdk-go/awscdk.(*jsiiProxy_App).Synth(0xc00009a270, 0x0, 0x70992e, 0x11)
        /home/ubuntu/environment/cdk/cdk-project-go/vendor/github.com/aws/aws-cdk-go/awscdk/awscdk.go:395 +0xb5
main.main()
        /home/ubuntu/environment/cdk/cdk-project-go/cdk-project-go.go:52 +0xfa
exit status 2
```

I was able to reproduce the issue with the default app that is created via `cdk init --language=go app`

Here is my code:

```go
type Aspect struct{}

func (a *Aspect) Visit(node awscdk.IConstruct) {
        awscdk.Annotations_Of(node).AddInfo(jsii.String("Hello"))
}

type CdkProjectGoStackProps struct {
        awscdk.StackProps
}

func NewCdkProjectGoStack(scope constructs.Construct, id string, props *CdkProjectGoStackProps) awscdk.Stack {
        var sprops awscdk.StackProps
        if props != nil {
                sprops = props.StackProps
        }
        stack := awscdk.NewStack(scope, &id, &sprops)
        
        // The code that defines your stack goes here

        // as an example, here's how you would define an AWS SNS topic:
        awssns.NewTopic(stack, jsii.String("MyTopic"), &awssns.TopicProps{
                DisplayName: jsii.String("MyCoolTopic"),
        })

        return stack
}

func main() {
        app := awscdk.NewApp(nil)

        myStack := NewCdkProjectGoStack(app, "CdkProjectGoStack", &CdkProjectGoStackProps{
                awscdk.StackProps{
                        Env: env(),
                },
        })

        aspect := &Aspect{}

        awscdk.Aspects_Of(myStack).Add(aspect)


        app.Synth(nil)
}
```

**Comment by RomainMuller** [comment]
@all-contributors add @corymhall for bug

**Comment by RomainMuller** [comment]
Thanks for reporting this! I have been able to reproduce this, and have identified a fix for that. I'll submit a PR shortly (a draft, though - as I still have to write a test that covers the previously broken case).
