### ISSUE TITLE
node 16.0.0 deprecation warning - (node:67086) [DEP0148]

### ISSUE THREAD

**Issue by pgollucci** [aws/jsii#2808]
## :bug: Bug Report

This is in projen, but shouldn't be specific.

```shell
npx projen build
........
🤖 build » package | jsii-pacmak
(node:67086) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/pgollucci/src/github.com/forked/pgollucci/projen/node_modules/yaml/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
### Affected Languages

- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 1.28.0 (build 1801f4f), typescript 3.9.9

* **Platform:**     Darwin jlhewitt.fios-router.home 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 03:57:04 PST 2021; root:xnu-7195.101.1~4/RELEASE_X86_64 x86_64

node --version                                                                                
v16.0.0

### Verbose Log

```shell
node --trace-deprecation node_modules/.bin/jsii-pacmak --verbose
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'dotnet' for 0 modules
[jsii-pacmak] [INFO] Packaging 'go' for 0 modules
[jsii-pacmak] [INFO] Packaging 'java' for projen
[jsii-pacmak] [INFO] Packaging 'js' for projen
[jsii-pacmak] [INFO] Packaging 'python' for projen
[jsii-pacmak] [INFO] dotnet finished
[jsii-pacmak] [INFO] go finished
(node:73959) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/pgollucci/src/github.com/forked/pgollucci/projen/node_modules/yaml/package.json.
Update this package.json to use a subpath pattern like "./*".
    at emitFolderMapDeprecation (node:internal/modules/esm/resolve:69:11)
    at packageExportsResolve (node:internal/modules/esm/resolve:542:7)
    at resolveExports (node:internal/modules/cjs/loader:477:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:517:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at Object.resolveDependencyDirectory (/Users/pgollucci/src/github.com/forked/pgollucci/projen/node_modules/jsii-pacmak/lib/util.js:18:33)
    at /Users/pgollucci/src/github.com/forked/pgollucci/projen/node_modules/jsii-pacmak/lib/dependency-graph.js:44:36
    at Array.map (<anonymous>)
    at real$traverseDependencyGraph (/Users/pgollucci/src/github.com/forked/pgollucci/projen/node_modules/jsii-pacmak/lib/dependency-graph.js:43:41)
[jsii-pacmak] [INFO] js finished
[jsii-pacmak] [INFO] python finished
[jsii-pacmak] [INFO] java finished
[jsii-pacmak] [INFO] Packaged. java (52.2s) | python (26.3s) | js (12.4s) | npm pack (3.6s) | load jsii (0.5s) | dotnet (0.0s) | go (0.0s) | cleanup (???)
```

**Comment by RomainMuller** [comment]
Are you able to pinpoint which part of the `package.json` is responsible for this warning?
I don't know that we are using `exports` maps ourselves at this point..?
