### ISSUE TITLE
CloudArtifact.manifest cannot be read via jsii

### ISSUE THREAD

**Issue by rabbittsoup** [aws/jsii#2829]
Error thrown when retrieving the manifest attribute of a CloudArtifact.

### Reproduction Steps

```
from aws_cdk.core import App, Stack
app = App()
Stack(app, 'Stack')
assembly = app.synth()
for artifact in assembly.artifacts:
    artifact.manifest
```
### What did you expect to happen?

I expect artifact.manifest to return an ArtifactManifest

### What actually happened?

jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"stability":"stable","summary":"A file relative to the assembly root which contains the CloudFormation template for this stack."},"immutable":true,"locationInModule":{"filename":"lib/cloud-assembly/artifact-schema.ts","line":9},"name":"templateFile","type":{"primitive":"string"}}
      at nullAndOk (/tmp/tmp5j7tkg0q/lib/program.js:9318:23)
      at Object.serialize (/tmp/tmp5j7tkg0q/lib/program.js:8843:25)
      at Kernel._fromSandbox (/tmp/tmp5j7tkg0q/lib/program.js:8528:69)
      at Kernel.get (/tmp/tmp5j7tkg0q/lib/program.js:7943:34)
      at KernelHost.processRequest (/tmp/tmp5j7tkg0q/lib/program.js:9479:36)
      at KernelHost.run (/tmp/tmp5j7tkg0q/lib/program.js:9442:22)
      at Immediate._onImmediate (/tmp/tmp5j7tkg0q/lib/program.js:9443:46)
      at processImmediate (internal/timers.js:461:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    artifact.manifest
  File ".../lib/python3.8/site-packages/aws_cdk/cx_api/__init__.py", line 252, in manifest
    return typing.cast(aws_cdk.cloud_assembly_schema.ArtifactManifest, jsii.get(self, "manifest"))
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 118, in _recursize_dereference
    return _reference_map.resolve_reference(kernel, d)
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 111, in resolve
    insts = [
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 113, in <listcomp>
    **{
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 114, in <dictcomp>
    python_name: kernel.get(remote_struct, jsii_name)
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 118, in _recursize_dereference
    return _reference_map.resolve_reference(kernel, d)
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 111, in resolve
    insts = [
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 113, in <listcomp>
    **{
  File ".../lib/python3.8/site-packages/jsii/_reference_map.py", line 114, in <dictcomp>
    python_name: kernel.get(remote_struct, jsii_name)
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File ".../lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 301, in get
    response = self.provider.get(
  File ".../lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 347, in get
    return self._process.send(request, GetResponse)
  File ".../lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"stability":"stable","summary":"A file relative to the assembly root which contains the CloudFormation template for this stack."},"immutable":true,"locationInModule":{"filename":"lib/cloud-assembly/artifact-schema.ts","line":9},"name":"templateFile","type":{"primitive":"string"}}
Subprocess exited with error 1

### Environment

  - **CDK CLI Version: 1.100.0 (build d996c6d)**
  - **Framework Version: 1.100.0**
  - **Node.js Version: v14.16.0**
  - **OS: Amazon Linux 2**
  - **Language (Version): Python 3.8**

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Since it looks like this has been bounced around quite a bit, I have updated priority to `p1`, if this doesnt accurately reflect the severity, please downgrade
