### ISSUE TITLE
go: #STDERR> go: awscdkawslambda@v1.104.0: malformed module path "awscdkawslambda": missing dot in first path element

### ISSUE THREAD

**Issue by pgollucci** [aws/jsii#2842]
A tar.gz of the output dir from jsii-packmak for go.

[p6namer.tar.gz](https://github.com/aws/jsii/files/6487788/p6namer.tar.gz)

```shell

/Users/pgollucci/src/github.com/original/p6m7g8/p6-namer
npx jsii-pacmak -t go -o /tmp/go-pacmak -f -v --no-clean
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'go' for p6-namer
[jsii-pacmak] [INFO] [/tmp/go-pacmak/go/p6namer] Content of local.go.mod file:
module github.com/p6m7g8/p6-namer/p6namer

go 1.16

require (
        github.com/aws/jsii-runtime-go v1.29.0
        awscdkawslambda v1.104.0
        awscdkawslambdanodejs v1.104.0
        awscdkcore v1.104.0
        awscdkcustomresources v1.104.0
        github.com/aws/constructs-go/constructs/v3 v3.3.75
        awscdkawsapplicationautoscaling v1.104.0 // indirect
        awscdkawscloudwatch v1.104.0 // indirect
        awscdkawscodeguruprofiler v1.104.0 // indirect
        awscdkawsec2 v1.104.0 // indirect
        awscdkawsecr v1.104.0 // indirect
        awscdkawsecrassets v1.104.0 // indirect
        awscdkawsefs v1.104.0 // indirect
        awscdkawsevents v1.104.0 // indirect
        awscdkawsiam v1.104.0 // indirect
        awscdkawskms v1.104.0 // indirect
        awscdkawslogs v1.104.0 // indirect
        awscdkawss3 v1.104.0 // indirect
        awscdkawss3assets v1.104.0 // indirect
        awscdkawssigner v1.104.0 // indirect
        awscdkawssqs v1.104.0 // indirect
        awscdkcxapi v1.104.0 // indirect
        awscdkawsautoscalingcommon v1.104.0 // indirect
        awscdkregioninfo v1.104.0 // indirect
        awscdkcloudassemblyschema v1.104.0 // indirect
        awscdkawsssm v1.104.0 // indirect
        awscdkassets v1.104.0 // indirect
        awscdkawscloudformation v1.104.0 // indirect
        awscdkawssns v1.104.0 // indirect
)


// Local packages:
[jsii-pacmak] [WARN] Failed building go
[jsii-pacmak] [INFO] Generated code for go retained at /var/folders/kc/8rzdqjhd7hg5zf33fh7vgkrm0000gn/T/npm-packRNuw8W
[jsii-pacmak] [WARN] go failed
Error: Command (go mod download -modfile local.go.mod) failed with status 1:
#STDERR> go: awscdkawslambda@v1.104.0: malformed module path "awscdkawslambda": missing dot in first path element
#STDERR> 
#STDOUT> 
    at ChildProcess.<anonymous> (/Users/pgollucci/src/github.com/original/p6m7g8/p6-namer/node_modules/jsii-pacmak/lib/util.js:120:27)
    at Object.onceWrapper (node:events:472:26)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:365:28)
    at Pipe.<anonymous> (node:net:661:12)
```

**Comment by pgollucci** [comment]
See also https://github.com/p6m7g8/p6-namer/runs/2363861537#step:6:43

**Comment by pgollucci** [comment]
```
npx jsii --version
1.29.0 (build 41df200), typescript 3.9.9
```
```
uname -a    
Darwin jlhewitt.fios-router.home 20.5.0 Darwin Kernel Version 20.5.0: Thu Apr 15 05:31:19 PDT 2021; root:xnu-7195.120.38.111.1~4/RELEASE_X86_64 x86_64
```

**Comment by pgollucci** [comment]
https://cdk-dev.slack.com/archives/C01C8R4K2E6/p1620744658027600

**Comment by pgollucci** [comment]
![tasks_json_—_p6-namer](https://user-images.githubusercontent.com/34295/118371790-2e29de00-b57c-11eb-9f8b-4b33c45ad2ff.jpg)

**Comment by pgollucci** [comment]
Should that 'require' be an 'import' in the generated go code?

Also, the imports should look like this
```golang
  "github.com/aws/aws-cdk-go/aws-s3"
```

**Comment by pgollucci** [comment]
```shell
gh repo clone aws/jsii
cd jsii
yarn
lerna run --concurrency 8 --stream build
lerna run --concurrency 8 --stream test 
cd packages/@jsii/go-runtime

yarn run --verbose test 
yarn run v1.22.10
verbose 0.165454868 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/go-runtime/.npmrc".
verbose 0.165806323 Checking for configuration file "/Users/pgollucci/.npmrc".
verbose 0.166020686 Checking for configuration file "/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/etc/npmrc".
verbose 0.166220922 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/go-runtime/.npmrc".
verbose 0.166403224 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/.npmrc".
verbose 0.166546303 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/.npmrc".
verbose 0.166702126 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/.npmrc".
verbose 0.166835265 Found configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/.npmrc".
verbose 0.167248557 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/.npmrc".
verbose 0.167402003 Checking for configuration file "/Users/pgollucci/src/github.com/focused/.npmrc".
verbose 0.167528468 Checking for configuration file "/Users/pgollucci/src/github.com/.npmrc".
verbose 0.167715119 Checking for configuration file "/Users/pgollucci/src/.npmrc".
verbose 0.167886428 Checking for configuration file "/Users/pgollucci/.npmrc".
verbose 0.168085974 Checking for configuration file "/Users/.npmrc".
verbose 0.170007376 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/go-runtime/.yarnrc".
verbose 0.170177877 Checking for configuration file "/Users/pgollucci/.yarnrc".
verbose 0.170321081 Found configuration file "/Users/pgollucci/.yarnrc".
verbose 0.170686029 Checking for configuration file "/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/etc/yarnrc".
verbose 0.170899632 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/go-runtime/.yarnrc".
verbose 0.171086135 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/.yarnrc".
verbose 0.171289375 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/packages/.yarnrc".
verbose 0.17143544 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/.yarnrc".
verbose 0.171566043 Found configuration file "/Users/pgollucci/src/github.com/focused/aws/jsii/.yarnrc".
verbose 0.171879095 Checking for configuration file "/Users/pgollucci/src/github.com/focused/aws/.yarnrc".
verbose 0.172065083 Checking for configuration file "/Users/pgollucci/src/github.com/focused/.yarnrc".
verbose 0.17220098 Checking for configuration file "/Users/pgollucci/src/github.com/.yarnrc".
verbose 0.172379561 Checking for configuration file "/Users/pgollucci/src/.yarnrc".
verbose 0.172584732 Checking for configuration file "/Users/pgollucci/.yarnrc".
verbose 0.172747903 Found configuration file "/Users/pgollucci/.yarnrc".
verbose 0.173056157 Checking for configuration file "/Users/.yarnrc".
verbose 0.177124764 current time: 2021-05-16T13:30:39.578Z
$ (cd jsii-runtime-go && go test ./...)
go: errors parsing go.mod:
/Users/pgollucci/src/github.com/focused/aws/jsii/packages/@jsii/go-runtime/jsii-runtime-go/go.mod:10: unknown directive: retract
verbose 0.299913119 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:790:113)
    at /Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:34550:30
    at Generator.throw (<anonymous>)
    at step (/Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/pgollucci/src/github.com/p6/nodenv/nodenv/versions/14.16.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MrArnoldPalmer** [comment]
It looks like we have a bug with how we are building CDK to go. No `moduleName` is specified in the cdk modules `jsii.targets.go` so its not output to the .jsii file and then when you build a package depending on these the module names aren't included correctly in `go.mod`.

Might just be manually specifying the module names in all package.json files. I'll see if I can fix this.

**Comment by nicl** [comment]
Just to update, I am hitting this too I think:

```
Error: Command (go mod tidy -modfile local.go.mod) failed with status 1:
#STDERR> go: awscdkassets@v1.132.0: malformed module path "awscdkassets": missing dot in first path element
#STDERR> go: downloading github.com/aws/jsii-runtime-go v1.43.0
#STDERR> go: awscdkassets@v1.132.0: malformed module path "awscdkassets": missing dot in first path element
```

with JSII:

```
$ npx jsii --version
1.43.0 (build b69a797), typescript 3.9.10
```

and the local.go.mod file generated:

```
module github.com/guardian/cdk

go 1.16

require (
	github.com/aws/jsii-runtime-go v1.43.0
	awscdkawsapigateway v1.132.0
	awscdkawsautoscaling v1.132.0
	awscdkawscloudwatchactions v1.132.0
	awscdkawsec2 v1.132.0
	awscdkawsecr v1.132.0
	awscdkawsecs v1.132.0
	awscdkawselasticloadbalancing v1.132.0
	awscdkawselasticloadbalancingv2 v1.132.0
	awscdkawseventstargets v1.132.0
	awscdkawsiam v1.132.0
	awscdkawskinesis v1.132.0
	awscdkawslambda v1.132.0
	awscdkawslambdaeventsources v1.132.0
	awscdkawsrds v1.132.0
	awscdkawss3 v1.132.0
	awscdkawsstepfunctions v1.132.0
	awscdkawsstepfunctionstasks v1.132.0
	awscdkcore v1.132.0
	awscdkawscertificatemanager v1.132.0 // indirect
	awscdkawscloudwatch v1.132.0 // indirect
	awscdkawscognito v1.132.0 // indirect
	awscdkawslogs v1.132.0 // indirect
	awscdkawss3assets v1.132.0 // indirect
	awscdkcxapi v1.132.0 // indirect
	github.com/aws/constructs-go/constructs/v3 v3.3.161 // indirect
	awscdkawsacmpca v1.132.0 // indirect
	awscdkawsroute53 v1.132.0 // indirect
	awscdkcloudassemblyschema v1.132.0 // indirect
	awscdkregioninfo v1.132.0 // indirect
	awscdkawsapplicationautoscaling v1.132.0 // indirect
	awscdkawscodeguruprofiler v1.132.0 // indirect
	awscdkawsecrassets v1.132.0 // indirect
	awscdkawsefs v1.132.0 // indirect
	awscdkawsevents v1.132.0 // indirect
	awscdkawskms v1.132.0 // indirect
	awscdkawssigner v1.132.0 // indirect
	awscdkawssqs v1.132.0 // indirect
	awscdkawsautoscalingcommon v1.132.0 // indirect
	awscdkawsssm v1.132.0 // indirect
	awscdkassets v1.132.0 // indirect
	awscdkcustomresources v1.132.0 // indirect
	awscdkawscloudformation v1.132.0 // indirect
	awscdkawssns v1.132.0 // indirect
	awscdkawscodestarnotifications v1.132.0 // indirect
	awscdkawsautoscalinghooktargets v1.132.0 // indirect
	awscdkawsroute53targets v1.132.0 // indirect
	awscdkawssecretsmanager v1.132.0 // indirect
	awscdkawsservicediscovery v1.132.0 // indirect
	awscdkawssnssubscriptions v1.132.0 // indirect
	awscdkawscloudfront v1.132.0 // indirect
	awscdkawsglobalaccelerator v1.132.0 // indirect
	awscdkawssam v1.132.0 // indirect
	awscdkawscodebuild v1.132.0 // indirect
	awscdkawscodepipeline v1.132.0 // indirect
	awscdkawskinesisfirehose v1.132.0 // indirect
	awscdkawscodecommit v1.132.0 // indirect
	awscdkawsdynamodb v1.132.0 // indirect
	awscdkawss3notifications v1.132.0 // indirect
	awscdkawseks v1.132.0 // indirect
	awscdklambdalayerawscli v1.132.0 // indirect
	awscdklambdalayerkubectl v1.132.0 // indirect
	awscdklambdalayernodeproxyagent v1.132.0 // indirect
)


// Local packages:
```

**Comment by RomainMuller** [comment]
Is this still an issue? I see the last report was in November 2021, and I don't really have much in way of an actionnable reproduction here...?
