### ISSUE TITLE
`jsii-pacmak` failing to build .Net assembly in CDK v2

### ISSUE THREAD

**Issue by hnishar** [aws/jsii#3081]
### Affected Languages
- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [x] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version: 1.39.0**
* **Platform: Linux docker-desktop**

### What is the problem?

Repo: https://github.com/hnishar/jsii-pacmak-bug/tree/main

Reproduction steps:
* git clone git@github.com:hnishar/jsii-pacmak-bug.git
* docker run -u root --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node14
* npm install
* npm run jsii
* npm run jsii-pacmak

### Verbose Log

```
root@docker-desktop:/tmp/jsii-pacmak-bug# npm run jsii-pacmak

> jsii-pacmak-bug@1.0.0 jsii-pacmak /tmp/jsii-pacmak-bug
> jsii-pacmak

[jsii-pacmak] [WARN] Exception occurred, not cleaning up /tmp/npm-packtPwn6V
[jsii-pacmak] [WARN] dotnet failed
Error: All attempts failed. Last error: Command (dotnet build --force --configuration Release) failed with status 1:
#STDERR>
#STDOUT> Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
#STDOUT> Copyright (C) Microsoft Corporation. All rights reserved.
#STDOUT>
#STDOUT>   Determining projects to restore...
#STDOUT>   Restored /tmp/npm-packtPwn6V/Amazon.Constructs.AWS.Test/Amazon.Constructs.AWS.Test.csproj (in 281 ms).
#STDOUT> Amazon/Constructs/AWS/Test/CdkWorkshopStack.cs(8,48): error CS0234: The type or namespace name 'Construct' does not exist in the namespace 'Amazon.Constructs' (are you missing an assembly reference?) [/tmp/npm-packtPwn6V/Amazon.Constructs.AWS.Test/Amazon.Constructs.AWS.Test.csproj]
#STDOUT> Amazon/Constructs/AWS/Test/CdkWorkshopStack.cs(24,36): error CS0246: The type or namespace name 'DeputyProps' could not be found (are you missing a using directive or an assembly reference?) [/tmp/npm-packtPwn6V/Amazon.Constructs.AWS.Test/Amazon.Constructs.AWS.Test.csproj]
#STDOUT>
#STDOUT> Build FAILED.
#STDOUT>
#STDOUT> Amazon/Constructs/AWS/Test/CdkWorkshopStack.cs(8,48): error CS0234: The type or namespace name 'Construct' does not exist in the namespace 'Amazon.Constructs' (are you missing an assembly reference?) [/tmp/npm-packtPwn6V/Amazon.Constructs.AWS.Test/Amazon.Constructs.AWS.Test.csproj]
#STDOUT> Amazon/Constructs/AWS/Test/CdkWorkshopStack.cs(24,36): error CS0246: The type or namespace name 'DeputyProps' could not be found (are you missing a using directive or an assembly reference?) [/tmp/npm-packtPwn6V/Amazon.Constructs.AWS.Test/Amazon.Constructs.AWS.Test.csproj]
#STDOUT>     0 Warning(s)
#STDOUT>     2 Error(s)
#STDOUT>
#STDOUT> Time Elapsed 00:00:01.43
#STDOUT>
    at retry (/tmp/jsii-pacmak-bug/node_modules/jsii-pacmak/lib/util.js:69:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DotnetBuilder.buildModules (/tmp/jsii-pacmak-bug/node_modules/jsii-pacmak/lib/targets/dotnet.js:39:13)
    at async Promise.all (index 0)
    at async Object.pacmak (/tmp/jsii-pacmak-bug/node_modules/jsii-pacmak/lib/index.js:56:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsii-pacmak-bug@1.0.0 jsii-pacmak: `jsii-pacmak`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsii-pacmak-bug@1.0.0 jsii-pacmak script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-19T15_27_20_176Z-debug.log
```

**Comment by NGL321** [comment]
Hey @hnishar,

In v2 we actually have a package called `Constructs`. I believe this may be what is causing the conflict. Is this something you were potentially missing?

If I am misunderstanding the issue, please let me know.
