### ISSUE TITLE
ENOENT: no such file or directory, open 'node_modules/@aws-sdk/client-secrets-manager/.jsii'

### ISSUE THREAD

**Issue by revmischa** [aws/jsii#3433]
## :bug: Bug Report

Maybe related to #3379 ?

### Affected Languages

- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:* 1.55.0
* **Platform:**     macOS

### What is the problem?
Trying to build https://github.com/jetbridge/cognito-oidc-cdk-construct

```
➜  cognito-oidc-cdk-construct git:(master) ✗ nrb

> cognito-oidc-cdk-construct@0.0.0 build
> npx projen build

👾 build » default | node .projenrc.js
👾 build » compile | jsii --silence-warnings=reserved-word --no-fix-peer-dependencies
Error: Error: Error loading /Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/@aws-sdk/client-secrets-manager/.jsii: Error: ENOENT: no such file or directory, open '/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/@aws-sdk/client-secrets-manager/.jsii'
    at DependencyResolver.loadAssembly (/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/lib/project-info.js:197:19)
    at async DependencyResolver.loadAssemblyAndRecurse (/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/lib/project-info.js:177:26)
    at async DependencyResolver.resolveDependency (/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/lib/project-info.js:168:29)
    at async DependencyResolver.discoverDependencyTree (/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/lib/project-info.js:128:30)
    at async Object.loadProjectInfo (/Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/lib/project-info.js:51:22)
    at async /Users/cyber/dev/cognito-oidc-cdk-construct/node_modules/jsii/bin/jsii.js:78:66
👾 Task "build » compile" failed when executing "jsii --silence-warnings=reserved-word --no-fix-peer-dependencies" (cwd: /Users/cyber/dev/cognito-oidc-cdk-construct)
```

**Comment by GEMISIS** [comment]
Seeing the same issue for the aws-sdk:
```bash
Error: Error: Error loading C:\Users\XXXX\Documents\GitHub\discord-bot-cdk-construct\node_modules\aws-sdk\.jsii: Error: ENOENT: no such file or directory, open 'C:\Users\XXXX\Documents\GitHub\discord-bot-cdk-construct\node_modules\aws-sdk\.jsii'
```

**Comment by GEMISIS** [comment]
Seems to be an issue caused by having certain things as dependencies or peer dependencies. In my instance, including the aws-sdk as a dependency (so it gets bundled properly with esbuild for my Lambda function) is what is breaking this.

**Comment by MrArnoldPalmer** [comment]
JSII requires that dependencies that aren't JSII modules be included in the `bundledDependencies` of your package.json. Since they don't have JSII bindings generated, none of their types can be included in the public API of a JSII module.

Check out the docs https://aws.github.io/jsii/user-guides/lib-author/typescript-restrictions/#dependencies for more information.

If doesn't solve feel free to reopen.
