### ISSUE TITLE
Unable to run jsii watch

### ISSUE THREAD

**Issue by Chriscbr** [aws/jsii#3494]
### Describe the bug

Running `jsii -w` in my jsii-based projects causes an error:

```
/Volumes/workplace/cdk8s-core/node_modules/jsii/bin/jsii.js:97
    const allDiagnostics = [...projectInfoDiagnostics, ...emitResult.diagnostics];
                                                                     ^

TypeError: Cannot read properties of undefined (reading 'diagnostics')
    at /Volumes/workplace/cdk8s-core/node_modules/jsii/bin/jsii.js:97:70
    at Object.<anonymous> (/Volumes/workplace/cdk8s-core/node_modules/jsii/bin/jsii.js:104:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Volumes/workplace/cdk8s-core/node_modules/jsii/bin/jsii:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

### Expected Behavior

Expected the project to compile and "watch" for updated files normally.

### Current Behavior

An error occurred.

### Reproduction Steps

Check out [cdk8s-core](https://github.com/cdk8s-team/cdk8s-core) locally and then run `yarn` followed by `npx jsii -w`. I also had this error occur in [projen](https://github.com/projen/projen) and [cdk-dynamo-table-viewer](https://github.com/cdklabs/cdk-dynamo-table-viewer).

### Additional Information/Context

Using node v16.14.2, yarn v1.22.18, npm v8.5.0

### SDK version used

jsii v1.56.0

### Environment details (OS name and version, etc.)

macOS 12.3.1

**Comment by yuth** [comment]
Fixed in #3487
