### ISSUE TITLE
Python build fails with Cannot read property distName of undefined

### ISSUE THREAD

**Issue by markussiebert** [aws/jsii#3507]
### Describe the bug

I can't build python target with jsii even if i have this in my package.json

```
"jsii": {
    "outdir": "dist",
    "targets": {
      "python": {
        "distName": "cdk-sops-secrets",
        "module": "cdk_sops_secrets"
      }
    },
    "tsc": {
      "outDir": "lib",
      "rootDir": "src"
    }
  },
```

```
npx jsii-pacmak -v --target python
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'python' for cdk-sops-secrets
[jsii-pacmak] [WARN] python failed
TypeError: Cannot read property 'distName' of undefined
    at PythonGenerator.onBeginAssembly (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/targets/python.js:1689:56)
    at PythonGenerator.generate (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/generator.js:52:14)
    at Python.generateCode (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/target.js:29:28)
    at async Python.generateCode (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/targets/python.js:32:9)
    at async Function.make (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/util.js:227:36)
    at async IndependentPackageBuilder.buildModule (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/builder.js:42:21)
    at async Promise.all (index 0)
    at async IndependentPackageBuilder.buildModules (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/builder.js:31:13)
    at async Promise.all (index 0)
    at async Object.pacmak (/Users/markussiebert/github/cdk-sops-secrets/node_modules/jsii-pacmak/lib/index.js:61:9)
```

### Expected Behavior

It should build

### Current Behavior

I get the error posted earlier

### Reproduction Steps

try to build 

https://github.com/markussiebert/cdk-sops-secrets/tree/feat/deployPyPI

with 

npx jsii-pacmak -v --target python

### Possible Solution

no idea

### SDK version used

jsii-pacmak@^1.57.0:   version "1.57.0"   resolved "https://registry.yarnpkg.com/jsii-pacmak/-/jsii-pacmak-1.57.0.tgz#9d8636f64991ab740658b96df393590c7156b8dd"   integrity sha512-yUIuhVqovNEE8Oq0BKVauiv1/5AT1JguhsuKkB4AWTxdkXHxOkv4eVA/w4jiCBaGjbwVg7BjgWR8zuMuNCU98w==   dependencies:     "@jsii/check-node" "1.57.0"     "@jsii/spec" "^1.57.0"     clone "^2.1.2"     codemaker "^1.57.0"     commonmark "^0.30.0"     escape-string-regexp "^4.0.0"     fs-extra "^9.1.0"     jsii-reflect "^1.57.0"     jsii-rosetta "^1.57.0"     semver "^7.3.5"     spdx-license-list "^6.5.0"     xmlbuilder "^15.1.1"     yargs "^16.2.0"

### Environment details (OS name and version, etc.)

mac

**Comment by rafalkrupinski** [comment]
Have the same issue using pnpm and pacmak 1.63.1 (build 185bb34).
@markussiebert
