### ISSUE TITLE
Java: Infinite recursion constructing CfnFlowLog

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#353]
Reported via email:

----------

Trying to create a CfnFlowLog resource using the Java CDK crashes the build with a StackOverflow.

I'm using version 0.22 of the Java CDK.

This is the resource I'm trying to create (and I've tried altering the params a bit too but I still get the same error):

```
new CfnFlowLog(this, "VpcFlowLog", CfnFlowLogProps.builder()
.withResourceType("VPC")
.withResourceId(vpc.getVpcId())
.withLogDestinationType("s3")
.withLogDestination(bucket.getBucketArn())
.withTrafficType("ALL")
.build());
```

My current workaround is to construct the same FlowLog resource use a low-level Resource() instead. That seems to build just fine.

The error I was getting:

```
[exec] Exception in thread "main" java.lang.StackOverflowError
[exec] at com.fasterxml.jackson.databind.node.NodeCursor$ObjectCursor.currentHasChildren(NodeCursor.java:245)
[exec] at com.fasterxml.jackson.databind.node.TreeTraversingParser.nextToken(TreeTraversingParser.java:131)
[exec] at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:825)
[exec] at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:246)
[exec] at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:97)
[exec] at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:82)
[exec] at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
[exec] at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
[exec] at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[exec] at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
[exec] at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
[exec] at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[exec] at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
[exec] at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
[exec] at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2746)
[exec] at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:134)
[exec] at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
[exec] at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
[exec] at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
[exec] at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
[exec] at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
[exec] at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
(Truncated. Those last two lines repeat over and over for a while)
```

Let me know if you need any more info.

**Comment by RomainMuller** [comment]
I was unable to reproduce this issue with `1.20.0`, which confirms my presumption that this bug has been fixed a while back, but this issue wasn't closed at the time.

The reproduction code I used is:

```java
package com.myorg;

import software.amazon.awscdk.core.Construct;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.core.StackProps;

import software.amazon.awscdk.services.ec2.*;
import software.amazon.awscdk.services.s3.*;

public class FlowLogStack extends Stack {
    public FlowLogStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public FlowLogStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);

        final Vpc vpc = new Vpc(this, "Vpc");
        new CfnFlowLog(this, "vpcFlowLog", CfnFlowLogProps.builder()
            .resourceType("VPC")
            .resourceId(vpc.getVpcId())
            .logDestinationType("s3")
            .logDestination(new Bucket(this, "VpcFlowLogStore").getBucketArn())
            .trafficType("ALL")
            .build());
    }
}
```
