### ISSUE TITLE
Regression in 1.60 causing `SyntaxError: Unexpected token '?'`

### ISSUE THREAD

**Issue by mccartney** [aws/jsii#3586]
### Describe the bug

After upgrading from 1.59 to 1.60 the Terraform CDK runs end with a failure like below.

### Expected Behavior

no failure

### Current Behavior

```
/tmp/jsii-java-runtime946634785065350894/bin/jsii-runtime.js:3666
                this.untested = opts.untested ?? false;
                                               ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

### Reproduction Steps

Sorry, no concise self-contained snippet available. It's buried a few layers in our stack.
In short: Run Terraform CDK.

### SDK version used

1.12.234

### Environment details (OS name and version, etc.)

Linux, Docker container based on buildpack-deps:stretch-scm

**Comment by mccartney** [comment]
And now I can see the note in [the 1.60 release](https://github.com/aws/jsii/releases/tag/v1.60.0) which probably is relevant here:
> Beginning with this release, jsii packages no longer
support node 12. Users should migrate to a supported node release (14.x,
16.x, or 18.x).
i.e. #3547

**Comment by mccartney** [comment]
Closing then. It seems like it worked as intented.
