### ISSUE TITLE
CDKTF project panics (golang) in container run from linux but not mac

### ISSUE THREAD

**Issue by jaygorrell** [aws/jsii#3716]
### Describe the bug

I have a CDKTF project running in a Docker image. The image is pretty light: `focal-slim` with `terraform`, `nodejs`, and `cdktf` installed -- and then my golang application that uses cdktf/jsii to create AWS resources. 

When I run a statically-linked go binary, it works fine in my local mac environment (even in a Docker container) but gives errors when ran from the same container in a Kubernetes linux environment.

I know this is a lot of unrelated technology, but I do believe the underlying issue is most closely related to jsii as the problem only occurs when an AWS resource (via jsii) is encountered in the code.

### Expected Behavior

A barebones Docker image behaves similarly between mac and linux environments.

### Current Behavior

Running my Docker image locally (mac) and executing my golang binary generates the expected cdktf output. However, when the image is run in a Kubernetes environment (linux) and I exec in to run my binary, I get the following error:

```
panic: no response received from child process

goroutine 1 [running]:
github.com/aws/jsii-runtime-go/runtime.Load({0xf23b0d, 0x13}, {0xf168d2, 0x6}, {0x3190e40, 0x12662a9, 0x12662a9})
        external/com_github_aws_jsii_runtime_go/runtime/runtime.go:43 +0x91
github.com/hashicorp/cdktf-provider-aws-go/aws/v9/jsii.Initialize()
        external/com_github_hashicorp_cdktf_provider_aws_go_aws_v9/jsii/jsii.go:27 +0x85
github.com/hashicorp/cdktf-provider-aws-go/aws/v9.NewAwsProvider({0x7f033f190348?, 0xc000498800}, 0xc000498ba0, 0xc0004c69a0)
        external/com_github_hashicorp_cdktf_provider_aws_go_aws_v9/aws.go:63618 +0x45
[...]
```

### Reproduction Steps

N/A

### Additional Information/Context

I assume there is some sort of dependency needed that ins't included in the binary itself, even with Golang? I did verify that things work fine up until the moment I try to create an AWS resource (via github.com/hashicorp/cdktf-provider-aws-go/aws/v9). If I remove AWS resources and only have things like the Terraform backend configuration, I get no errors. I believe this is related to when the child node process is created?

I appreciate any guidance on the direction to explore for this type of issue. I'm a little stumped given the container runs correctly in a local environment.

### SDK version used

github.com/aws/jsii-runtime-go v1.63.2

### Environment details (OS name and version, etc.)

Mixed, details above

**Comment by jaygorrell** [comment]
Apologies, not a jsii issue afterall. This was a Kubernetes container resource limit -- but because the spawned child process isn't the primary process, the pod was not killed and it just silently failed.
