### ISSUE TITLE
fix(Issues with Release 1.73.0) - AWS CLI no longer working, jsii-macpak issues

### ISSUE THREAD

**Issue by biffgaut** [aws/jsii#3903]
### Describe the bug

We use the jsii/superchain:1-buster-slim-node14 in our build process to take advantage of JSII to release Java and Python versions of Soluions Constructs. In version 1.73.0 released  on 1/4/23:

* the AWS CLI no longer works
* All our usage of jsii-pacmak has stopped working

### Expected Behavior

AWS CLI works

jsii builds that worked in 1.72.0 continue to build

### Current Behavior

When running any aws cli command, even aws --version on a newly downloaded image, we get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.7/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.7/dist-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/lib/python3.7/dist-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/lib/python3.7/dist-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/lib/python3.7/dist-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/lib/python3.7/dist-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/lib/python3.7/dist-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/lib/python3.7/dist-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.7/dist-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/usr/local/lib/python3.7/dist-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```
This appears to be related to [this issue](https://github.com/aws/aws-sam-cli/issues/4527) and a dependency on the cryptography library.

When we run jsii-pacmak against our core folder, we get the following error once we start using v1.73.0 of the superchain image:

When we run it against our core folder on the 1/4 image, we get

```
/core# jsii-pacmak
[xmldom warning]	attribute "arguments" missed value!! "arguments" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "that" missed value!! "that" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "are" missed value!! "are" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "passed" missed value!! "passed" instead!!
@#[line:1,col:1]
[xmldom warning]	attribute "arguments" missed value!! "arguments" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "that" missed value!! "that" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "are" missed value!! "are" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "passed" missed value!! "passed" instead!!
@#[line:1,col:1]
[xmldom warning]	attribute "arguments" missed value!! "arguments" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "that" missed value!! "that" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "are" missed value!! "are" instead2!!
@#[line:1,col:1]
[xmldom warning]	attribute "passed" missed value!! "passed" instead!!
@#[line:1,col:1]
[jsii-pacmak] [WARN] Failed building python
[jsii-pacmak] [WARN] python failed
Error: All attempts failed. Last error: Command (/tmp/npm-packyKhdlF/.env-zE8JKJ/bin/python -m pip install --no-input -r /Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/targets/python/requirements-dev.txt) failed with status 1:
#STDERR> Traceback (most recent call last):
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 33, in vendored
#STDERR>     __import__(vendored_name, globals(), locals(), level=0)
#STDERR> ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
#STDERR>
#STDERR> During handling of the above exception, another exception occurred:
#STDERR>
#STDERR> Traceback (most recent call last):
#STDERR>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#STDERR>     "__main__", mod_spec)
#STDERR>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
#STDERR>     exec(code, run_globals)
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
#STDERR>     from pip._internal import main as _main  # isort:skip # noqa
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/lib/python3.7/site-packages/pip/_internal/__init__.py", line 19, in <module>
#STDERR>     from pip._vendor.urllib3.exceptions import DependencyWarning
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
#STDERR>     vendored("cachecontrol")
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
#STDERR>     __import__(modulename, globals(), locals(), level=0)
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packyKhdlF/.env-zE8JKJ/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
#STDERR>   File "/usr/local/lib/python3.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
#STDERR>     from OpenSSL import crypto, SSL
#STDERR>   File "/usr/local/lib/python3.7/dist-packages/OpenSSL/crypto.py", line 3268, in <module>
#STDERR>     _lib.OpenSSL_add_all_algorithms()
#STDERR> AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
#STDERR>
#STDOUT>
    at retry (/Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/util.js:127:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Python.build (/Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/targets/python.js:68:9)
    at async IndependentPackageBuilder.buildModule (/Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/builder.js:48:20)
    at async Promise.all (index 0)
    at async IndependentPackageBuilder.buildModules (/Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/builder.js:31:13)
    at async Promise.all (index 4)
    at async pacmak (/Users/biffgaut/Documents/Active/AWS/Constructs/github/stack-description-error/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/index.js:66:9)
```

### Reproduction Steps

aws --version

jsii-pacmak

### Additional Information/Context

The environments are published jsii/superchain:1-buster-slim-node14 images:

* Working: jsii/superchain@sha256:80ee12fd2b143ff58d93c72c43985281bb6923370f8df93fcbb23834f0bfb5a7 (this is actually about 3 months old, but is the only old image where I had a SHA)
* Not working: jsii/superchain@sha256:sha256:e141efae388816c76743008eb95bc661e3dd12e4f142e5a859e4f067c484ae49

Please let me know if there is any info from our core folder that would assist in researching the issue (you can see our entire core folder in [github](https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/core))

### SDK version used

Docker image 1.73.0; jsii-mak 1.73.0

### Environment details (OS name and version, etc.)

5.10.124-linuxkit

**Comment by biffgaut** [comment]
I've replicated the issue using a small sample program from your documentation. These are the two files of interest:

**package.json**
```
{
  "name": "project-name",
  "version": "1.0.0",
  "description": "A demonstration jsii library",
  "main": "index.js",
  "scripts": {
    "build": "jsii",
    "build:watch": "jsii --watch",
    "package": "jsii-pacmak"
  },
  "keywords": [],
  "author": {
    "name": "John Doe",
    "email": "john.doe@acme.com"
  },
  "repository": {
    "url": "https://github.com/awslabs/aws-solutions-constructs.git"
  },
  "license": "ISC",
  "stability": "experimental",
  "types": "index.d.ts",
  "jsii": {
    "outdir": "dist",
    "versionFormat": "full",
    "targets": {
      "java": {
        "package": "software.amazon.module.jsiitest",
        "maven": {
          "groupId": "software.amazon.module",
          "artifactId": "jsiitest"
        }
      },
      "python": {
        "distName": "aws-solutions-construct.jsii-test",
        "module": "aws_solutions_constructs.jsii_test"
      },
      "dotnet": {
        "namespace": "Amazon.SolutionsConstructs.AWS",
        "packageId": "JsiiTest",
        "iconUrl": "https://raw.githubusercontent.com/aws/aws-cdk/master/logo/default-256-dark.png"
      }
    }
  },
  "devDependencies": {
    "jsii": "^1.73.0",
    "jsii-pacmak": "^1.73.0"
  }
}
```

**index.ts**
```
export interface GreeterProps {
  readonly greetee: string;
}

export class Greeter {
  private readonly greetee: string;

  public constructor(props: GreeterProps) {
    this.greetee = props.greetee;
  }

  public greet(): string {
    return `Hello, ${this.greetee}!`
  }
}
```

When I launch a container using sha256:80ee12fd2b143ff58d93c72c43985281bb6923370f8df93fcbb23834f0bfb5a7 and run the following commands:

```
npm run build
npm run package
```

The app appears to finish correctly and the dist tree is created. When I launch sha256:sha256:e141efae388816c76743008eb95bc661e3dd12e4f142e5a859e4f067c484ae49 and run the identical steps, when I attempt to package I get:

```
[jsii-pacmak] [WARN] Failed building python
[jsii-pacmak] [WARN] python failed
Error: All attempts failed. Last error: Command (/tmp/npm-packwsjh15/.env-rkL2RE/bin/python -m pip install --no-input -r /Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/targets/python/requirements-dev.txt) failed with status 1:
#STDERR> Traceback (most recent call last):
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 33, in vendored
#STDERR>     __import__(vendored_name, globals(), locals(), level=0)
#STDERR> ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
#STDERR>
#STDERR> During handling of the above exception, another exception occurred:
#STDERR>
#STDERR> Traceback (most recent call last):
#STDERR>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#STDERR>     "__main__", mod_spec)
#STDERR>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
#STDERR>     exec(code, run_globals)
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
#STDERR>     from pip._internal import main as _main  # isort:skip # noqa
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/lib/python3.7/site-packages/pip/_internal/__init__.py", line 19, in <module>
#STDERR>     from pip._vendor.urllib3.exceptions import DependencyWarning
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
#STDERR>     vendored("cachecontrol")
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/lib/python3.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
#STDERR>     __import__(modulename, globals(), locals(), level=0)
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
#STDERR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#STDERR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
#STDERR>   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
#STDERR>   File "/tmp/npm-packwsjh15/.env-rkL2RE/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
#STDERR>   File "/usr/local/lib/python3.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
#STDERR>     from OpenSSL import crypto, SSL
#STDERR>   File "/usr/local/lib/python3.7/dist-packages/OpenSSL/crypto.py", line 3268, in <module>
#STDERR>     _lib.OpenSSL_add_all_algorithms()
#STDERR> AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
#STDERR>
#STDOUT>
    at retry (/Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/util.js:127:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Python.build (/Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/targets/python.js:68:9)
    at async IndependentPackageBuilder.buildModule (/Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/builder.js:48:20)
    at async Promise.all (index 0)
    at async IndependentPackageBuilder.buildModules (/Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/builder.js:31:13)
    at async Promise.all (index 4)
    at async pacmak (/Users/biffgaut/Documents/Active/AWS/Constructs/clients/jsii-test/node_modules/jsii-pacmak/lib/index.js:66:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-name@1.0.0 package: `jsii-pacmak`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-name@1.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-06T21_39_54_249Z-debug.log
```

**Comment by rix0rrr** [comment]
The current superchain images have been fixed.
