### ISSUE TITLE
Make Jsii Thread Safe

### ISSUE THREAD

**Issue by fahhas-aws** [aws/jsii#4311]
### Describe the feature

Hello,

The Jsii Library is not thread safe. This has been confirmed several times using the CDK library in java. When attempting to build CDK templates in more than one thread, you are greeted with this error.

`Exception in thread "Thread-1" software.amazon.jsii.JsiiException: Malformed object reference. Expecting $jsii.byref
	at software.amazon.jsii.JsiiObjectRef.parse(JsiiObjectRef.java:52)
	at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:91)
	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:458)`

The current workaround is to synchronize requests via a lock in Java when performing any actions with CDK.

Please update jsii to be thread safe.

### Use Case

Attempting to build CloudFormation templates in more than one thread by leveraging CDK with Java.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.103.0

### Environment details (OS name and version, etc.)

Mac OS Ventura

**Comment by sthomson-wyn** [comment]
Duplicate of https://github.com/aws/jsii/issues/685
