### ISSUE TITLE
Python: loading JSII libraries into a REPL is sensitive to timeout

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#439]
If you load a JSII library in a REPL, wait a while, and then try to load another JSII library:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/aws_cdk/runtime_values/__init__.py", line 13, in <module>
    import aws_cdk.aws_ssm
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/aws_cdk/aws_ssm/__init__.py", line 14, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/aws-ssm", "0.27.0", __name__, "aws-ssm@0.27.0.jsii.tgz")
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/jsii/_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 184, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 326, in load
    return self._process.send(request, LoadResponse)
  File "/home/local/ANT/huijbers/Workspaces/PublicCDK/cdk-ci-cd/cdk-docs/python/venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 303, in send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

Looks like some pipe has been closed (due to a timeout?)

**Comment by garnaat** [comment]
How long did you wait?  I've tested locally for ~ 20 minutes and can't reproduce.

**Comment by rix0rrr** [comment]
Ah, maybe it's not a timeout then.
