### ISSUE TITLE
StackOverflowError with Java when overriding Stack.allocateLogicalId

### ISSUE THREAD

**Issue by mi-laf** [aws/jsii#4656]
### Describe the bug

CDK with Java produces `StackOverflowError`s when overriding `Stack.allocateLogicalId` (and having many resources in the stack).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Overriding `Stack.allocateLogicalId` should not cause a `StackOverflowError`.

### Current Behavior

There is a StackOverflowError when synthesizing the app:

	Exception in thread "main" java.lang.StackOverflowError
		at software.amazon.jsii.JsiiEngine.invokeMethod(JsiiEngine.java:482)
		at software.amazon.jsii.JsiiEngine.invokeCallbackMethod(JsiiEngine.java:461)
		at software.amazon.jsii.JsiiEngine.handleCallback(JsiiEngine.java:404)
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:171)
		at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:121)
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:197)
		at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:121)
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:197)
		at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:121)
		...
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:197)
		at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:121)
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:197)
		at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:121)
		at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:197)
	node:events:497
		throw er; // Unhandled 'error' event
		^
	Error: write EPIPE
		at afterWriteDispatched (node:internal/stream_base_commons:159:15)
		at writeGeneric (node:internal/stream_base_commons:150:3)
		at Socket._writeGeneric (node:net:958:11)
		at Socket._write (node:net:970:8)
	Error: write EPIPE
		at writeOrBuffer (node:internal/streams/writable:572:12)
		at _write (node:internal/streams/writable:501:10)
		at Writable.write (node:internal/streams/writable:510:10)
		at Socket.ondata (node:internal/streams/readable:1009:22)
		at Socket.emit (node:events:519:28)
		at addChunk (node:internal/streams/readable:561:12)
	Emitted 'error' event on Socket instance at:
		at Socket.onerror (node:internal/streams/readable:1028:14)
		at Socket.emit (node:events:519:28)
		at emitErrorNT (node:internal/streams/destroy:170:8)
		at emitErrorCloseNT (node:internal/streams/destroy:129:3)
		at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
	errno: -32,
	code: 'EPIPE',
	syscall: 'write'
	}

### Reproduction Steps

Put the following code in file call `Main.java` and run it with arguments "true" and "250" to create 250 buckets in a stack which overrides `Stack.allocateLogicalId`. This should reproduce the issue.

	import org.jetbrains.annotations.NotNull;
	import software.amazon.awscdk.App;
	import software.amazon.awscdk.CfnElement;
	import software.amazon.awscdk.Stack;
	import software.amazon.awscdk.services.s3.Bucket;
	import software.amazon.awscdk.services.s3.BucketProps;
	import software.constructs.Construct;

	public class Main {

		/**
		 * Creates an app with a single stack which just has a lot of buckets.
		 * arg 1: whether to use a stack which overrides Stack.allocateLogicalId ("true" or "false")
		 * arg 2: the number of buckets to create
		 */
		public static void main(final String[] args) {
			boolean overrideAllocateLogicalId = Boolean.parseBoolean(args[0]);
			int bucketCount = Integer.parseInt(args[1]);

			App app = new App();
			Stack stack = overrideAllocateLogicalId ? new AllocateLogicalIdOverridingStack(app, bucketCount) : new AllocateLogicalIdNotOverridingStack(app, bucketCount);
			System.out.println("Using " + stack.getClass().getName() + " to create " + bucketCount + " buckets.");
			app.synth();
			System.out.println("Successfully synthesized app.");
		}

		private abstract static class AbstractStack extends Stack {
			protected AbstractStack(Construct scope, int bucketCount) {
				super(scope);
				for (int i = 0; i < bucketCount; i++) {
					new Bucket(this, "bucket" + i, BucketProps.builder().bucketName("bucket" + i).enforceSsl(true).build());
				}
			}
		}

		private static class AllocateLogicalIdNotOverridingStack extends AbstractStack {
			private AllocateLogicalIdNotOverridingStack(Construct scope, int bucketCount) {
				super(scope, bucketCount);
			}
		}

		private static class AllocateLogicalIdOverridingStack extends AbstractStack {
			private AllocateLogicalIdOverridingStack(Construct scope, int bucketCount) {
				super(scope, bucketCount);
			}

			@Override
			public @NotNull String allocateLogicalId(@NotNull CfnElement cfnElement) {
				// could allocate special ids here
				return super.allocateLogicalId(cfnElement);
			}
		}
	}

### Possible Solution

Not overriding `Stack.allocateLogicalId` fixes the issue. This can be verified by running the example code with "false" and "250".

Adding JVM parameter `-Xss2m` to increase the stack size also fixes the issue. This is an easy work around. But if this is really necessary (in bigger stacks) and if there are any limits one should be aware of, especially when overriding `Stack.allocateLogicalId`, they should be documented in the respective [Javadoc](https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/Stack.html#allocateLogicalId(software.amazon.awscdk.CfnElement)).

### Additional Information/Context

The reason there is `.enforceSsl(true)` on the bucket (in example code) is that the problem was not reproducible without any bucket settings.

### CDK CLI Version

2.160.0

### Framework Version

2.160.0

### Node.js Version

v22.9.0

### OS

Linux

### Language

Java

### Language Version

Java 21 - Corretto-21.0.4.7.1 (build 21.0.4+7-LTS)

**Comment by jami3cressey** [comment]
Independently hit this on a different trigger surface — sharing root-cause analysis and a proposed one-line fix in case it's useful. tl;dr: this is not specific to `Stack.allocateLogicalId`; **any pattern that produces enough Node→Java callbacks during synth will hit it**, because `JsiiClient.getModuleNames` has no cache and `JsiiRuntime.requestResponse` is explicitly interruptible by callbacks.

## Second reproducer (same `processCallbackResponse ↔ requestResponse` recursion)

```java
public final class FlagAspect implements IAspect {
    @Override public void visit(IConstruct node) { /* empty */ }
}

App app = new App(...);
Aspects.of(app).add(new FlagAspect());
// build a moderately large tree (a real consumer service with ~hundreds of constructs across ~16 stacks is enough)
app.synth();   // StackOverflowError with the same JsiiRuntime.processCallbackResponse ↔ requestResponse recursion shape
```

An empty `visit()` body reproduces the crash, so it is not the aspect's logic — it is the callback mechanism itself. Same Java runtime / aws-cdk-lib pinned (cdk 2.257.0, jsii-runtime 1.131.0).

## Root cause (from the source)

`JsiiEngine.resolveJavaClass` (line 311 of jsii-runtime 1.131.0):

```java
Class<?> resolveJavaClass(final String fqn) {
    ...
    String moduleName = parts[0];
    JsonNode names = this.getClient().getModuleNames(moduleName);   // ← every call, no cache check
    ...
}
```

`JsiiClient.getModuleNames` (line 264):

```java
public JsonNode getModuleNames(final String moduleName) {
    ObjectNode req = makeRequest("naming");
    req.put("assembly", moduleName);
    JsonNode resp = this.runtime.requestResponse(req);   // synchronous Java→Node round-trip
    return resp.get("naming");
}
```

**No caching anywhere.** The naming map for an assembly is fetched fresh from Node every time `resolveJavaClass` is invoked for a cold-cache `nativeFromObjRef`. With a `-Djsii.debug=true` capture against my reproducer, I counted **616 `{"api":"naming","assembly":"aws-cdk-lib"}` requests in the seconds before the crash**.

The other half of the bug is that `JsiiRuntime.requestResponse` is documented and built to be interruptible:

```java
JsonNode requestResponse(final JsonNode request) {
    ...
    JsonNode resp = readNextResponse();
    ...
    // process synchronous callbacks (which 'interrupt' the response flow).
    if (resp.has("callback")) {
        return processCallbackResponse(resp);   // ← reuses the same Java stack frame
    }
    ...
}
```

So when Java sends a `naming` request and Node interrupts with a callback (because Node needed to call back into Java to fulfil the response — e.g., to evaluate a Lazy producer, resolve a token, attach an annotation, dispatch an aspect visit, or honour a `Stack.allocateLogicalId` override), Java handles that callback on the *current* Java stack frame. The callback handler may itself need to resolve a Java class for one of its arguments → fires another uncached `getModuleNames` → Node may interrupt that with another callback → frames compound → `StackOverflowError`.

The per-instance cache in `JsiiEngine.nativeFromObjRef` (`this.objects.get(objRef.getObjId())`) does exist, but it is keyed by **object instance ID, not by class FQN** — so distinct construct instances of the same type still each hit the cold path through `resolveJavaClass`.

## Why some Java CDK apps see it and others don't

- Small construct trees keep the obj-id cache warm and rarely hit `resolveJavaClass` → no opportunity for the interleaving.
- The original reporter's pattern (override `allocateLogicalId` + many resources) and mine (`IAspect.visit` + many resources) both produce many Node→Java callbacks whose arguments need class resolution. Either is enough to cross the recursion threshold on a real-sized tree.
- This is also why workarounds shaped like "increase `-Xss`" or "avoid the override / aspect" both work but only paper over the underlying behaviour.

## Proposed fix (one method, in `JsiiClient.java`)

Per-module naming is immutable for the lifetime of the jsii kernel — the assembly schema doesn't change mid-synth — so caching is trivially safe:

```java
private final Map<String, JsonNode> moduleNamingCache = new ConcurrentHashMap<>();

public JsonNode getModuleNames(final String moduleName) {
    return moduleNamingCache.computeIfAbsent(moduleName, name -> {
        ObjectNode req = makeRequest("naming");
        req.put("assembly", name);
        return this.runtime.requestResponse(req).get("naming");
    });
}
```

After this change, `resolveJavaClass` issues at most **one** `naming` request per assembly per JVM (a handful of assemblies across a typical CDK app) and the per-callback recursion opportunity collapses to that bounded number. The interruptibility of `requestResponse` remains intact; we just stop creating the opportunity for it to recurse on a hot path.

## Workaround pattern for affected consumers (until the fix lands)

For tree-wide synth-time checks (the case I needed `IAspect` for): drive the traversal from a single Java entry point instead of as N callbacks. An `App` subclass override is the simplest shape:

```java
private static final class MyApp extends App {
    MyApp(AppProps p) { super(p); }
    @Override public CloudAssembly synth() {
        for (IConstruct n : this.getNode().findAll()) {
            // type checks + Annotations.of(n).addWarning(...) etc.
        }
        return super.synth();
    }
}
```

One Java method dispatch, zero Node→Java callbacks for the traversal itself. Property reads still go Java→Node (and `nativeFromObjRef` keeps its instance cache warm). I'm shipping this pattern in our internal pipeline library — it eliminates the crash on a tree where the equivalent `IAspect` reliably blew the stack. Posting this in case the same workaround helps anyone else stuck here while the upstream caching fix is considered.

Happy to open a PR for the caching change if that would help move it forward.
