### ISSUE TITLE
Trying to use jsii to convert readme example to python immediately fails.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#573]
I added a `python: {}` section to my package.json.  Running jsii produced:

```
root@DESKTOP-UVPENCH:/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii# npm run package

> experiments@1.0.0 package /home/cyrusn/go/src/github.com/pulumi/pulumi/jsii
> jsii-pacmak -v

[jsii-pacmak] [INFO] Building experiments (java,dotnet,python,sphinx,js) into dist
TypeError: Cannot read property 'replace' of undefined
    at pythonModuleNameToFilename (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/targets/python.js:39:17)
    at Package.write (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/targets/python.js:814:47)
    at PythonGenerator.onEndAssembly (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/targets/python.js:1087:22)
    at PythonGenerator.generate (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/generator.js:72:14)
    at Python.generateCode (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/target.js:41:34)
    at <anonymous>
```

**Comment by RomainMuller** [comment]
That's because your python configuration is incorrect. This is now [documented](https://github.com/aws/jsii/blob/master/docs/configuration.md#configuring-python).
