### ISSUE TITLE
Simple code crashes .net generator.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#574]
My ts code:

```ts
export class HelloJsii {
    public stringOutput: IOutput<string>;
    private input: any;

    public sayHello(name: string) {
      return `Hello, ${name}!`;
    }

    public takeInput(input: Input<string>) {
        this.input = input;
    }

    public myInput() {
        return this.input;
    }
}

export interface IOutput<T> {
    val(): Promise<T>;
}

export type Input<T> = T | Promise<T> | IOutput<T>;
```

Causes this crash:

```
[jsii-pacmak] [INFO] Building experiments (java,dotnet,python,sphinx,js) into dist

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Amazon.JSII.Generator.Interface.InterfaceGenerator.CreateMethods()+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Amazon.JSII.Generator.Interface.InterfaceGenerator.CreateType() in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/Interface/InterfaceGenerator.cs:line 21
   at Amazon.JSII.Generator.TypeGeneratorBase`1.CreateSyntaxTree() in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/TypeGeneratorBase.cs:line 35
   at Amazon.JSII.Generator.AssemblyGenerator.<>c__DisplayClass4_0.<Save>g__SaveType|3(Type type) in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/AssemblyGenerator.cs:line 307
   at Amazon.JSII.Generator.AssemblyGenerator.Save(String packageOutputRoot, ISymbolMap symbols, Assembly assembly, String tarballFileName, String jsiiFileName) in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/AssemblyGenerator.cs:line 106
   at Amazon.JSII.Generator.AssemblyGenerator.Generate(String jsiiFile, String tarballPath, ISymbolMap symbols) in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/AssemblyGenerator.cs:line 92
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Amazon.JSII.Generator.CLI.Program.Main(String[] args) in /codebuild/output/src129887864/src/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator.CLI/Program.cs:line 11
Error: jsii-dotnet-generator exited with code null
    at ChildProcess.cli.once.code (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii-pacmak/lib/targets/dotnet.js:132:35)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by RomainMuller** [comment]
I reckon this problem no longer exists. Please re-open if I am mistaken.
