### ISSUE TITLE
Python 3.8.0: ImportError: cannot import name '_Union' from 'typing'

### ISSUE THREAD

**Issue by mikelane** [aws/jsii#913]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **Python Version:** 3.8.0
* **JSII Version:** 0.19.0 
* **Platform:** MacOS 10.15.1 Beta     

### What is the problem?

The jsii module was installed using pipenv v.2018-11-26 as a sub-dependency of `aws-cdk.core`. Whenever I execute any cdk CLI methods, like `cdk ls` or if I import CDK modules like `from aws_cdk import core` or `import jsii` in the python repl, I get an `ImportError` with the following traceback:

```bash
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6, in <module>
    import jsii
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/_runtime.py", line 6, in <module>
    from jsii import _reference_map
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/_reference_map.py", line 6, in <module>
    from ._kernel.types import JSClass, Referenceable
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from jsii._kernel.providers import BaseProvider, ProcessProvider
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from jsii._kernel.providers.process import ProcessProvider
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 15, in <module>
    import cattr  # type: ignore
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/Users/***/.local/share/virtualenvs/***/lib/python3.8/site-packages/cattr/_compat.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/Users/***/.pyenv/versions/3.8.0/lib/python3.8/typing.py)
Subprocess exited with error 1
```

This does not happen with python version 3.7.4.

**Comment by mikelane** [comment]
Digging deeper it appears that the cattrs module would support python 3.8 just fine, probably, but they are self-limiting to python 3.7 [here](https://github.com/Tinche/cattrs/blob/7311176e15970cba50c7c435a4e6e353c00bfeaf/src/cattr/_compat.py#L15). If this conditional [here](https://github.com/Tinche/cattrs/blob/7311176e15970cba50c7c435a4e6e353c00bfeaf/src/cattr/_compat.py#L29) would allow python 3.8, too, then this particular bug would be avoided (though, it isn't clear if there are other bugs of this kind). However, python 3.8 does not meet the condition, so 3.8 is directed to older, incompatible code [here](https://github.com/Tinche/cattrs/blob/7311176e15970cba50c7c435a4e6e353c00bfeaf/src/cattr/_compat.py#L86). This causes the ImportError that bubbles up to jsii.

**Comment by mikelane** [comment]
I submitted a PR to cattrs to address this: https://github.com/Tinche/cattrs/pull/73

**Comment by RomainMuller** [comment]
@mikelane - thanks for having and the research. It appears we are broken by upstream (that is unfortunate). I'm leaving this issue open waiting for the upstream issue to be fixed.

**Comment by robertoalvesneto** [comment]
It's happen on python 3.10.1

**Comment by lstnl** [comment]
ImportError: cannot import name 'Union' from 'types' (/usr/lib/python3.10/types.py)
