### ISSUE TITLE
Build steps for contributors

### ISSUE THREAD

**Issue by unicomp21** [aws/jsii#950]
I can get the build steps for docker to work on my Mac, but on ubuntu 18.04 it fails.  What am I doing wrong?

```
jdavis@jdavis-Inspiron-ubuntu:~/repo/github/jsii$ git checkout -b v0.20.1 v0.20.1
Switched to a new branch 'v0.20.1'
jdavis@jdavis-Inspiron-ubuntu:~/repo/github/jsii$ IMAGE=superchain
jdavis@jdavis-Inspiron-ubuntu:~/repo/github/jsii$ docker build -t ${IMAGE} ./superchain
Sending build context to Docker daemon  17.41kB
Step 1/24 : FROM amazonlinux:2
 ---> 6ef285e58e33
Step 2/24 : RUN yum -y install deltarpm
 ---> Using cache
 ---> 428d0c5f95e5
Step 3/24 : ENV DOTNET_CLI_TELEMETRY_OPTOUT=true                                                                                        DOTNET_RUNNING_IN_CONTAINER=true                                                                                        DOTNET_USE_POLLING_FILE_WATCHER=true                                                                                    NUGET_XMLDOC_MODE=skip
 ---> Using cache
 ---> 5044119c5fee
Step 4/24 : COPY gpg/mono.asc /tmp/mono.asc
 ---> Using cache
 ---> f6cc0d293c6d
Step 5/24 : RUN rpm --import "https://packages.microsoft.com/keys/microsoft.asc"                                                      && rpm -Uvh "https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm"                                  && rpm --import /tmp/mono.asc && rm -f /tmp/mono.asc                                                                    && curl -sSL "https://download.mono-project.com/repo/centos6-stable.repo"                                                   | tee /etc/yum.repos.d/mono-centos6-stable.repo                                                                     && yum -y install dotnet-sdk-3.0 dotnet-sdk-2.2 mono-devel powershell                                                   && yum clean all && rm -rf /var/cache/yum                                                                               && dotnet help
 ---> Using cache
 ---> 95ce900362cc
Step 6/24 : RUN yum -y install python3 python3-pip                                                                                    && python3 -m pip install --upgrade pip setuptools wheel twine                                                          && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> 7a16050300a1
Step 7/24 : ENV GEM_HOME /usr/local/bundle
 ---> Using cache
 ---> 28bd26cac35d
Step 8/24 : RUN amazon-linux-extras install ruby2.4                                                                                   && yum -y install gcc make ruby-devel rubygem-rdoc system-rpm-config                                                    && yum clean all && rm -rf /var/cache/yum                                                                               && echo 'install: --no-document' > /usr/local/etc/gemrc                                                                 && echo 'update: --no-document' >> /usr/local/etc/gemrc                                                                 && mkdir -p "$GEM_HOME"                                                                                                 && gem install 'bundler:~>1.17.2' 'bundler:~>2.0.2'
 ---> Using cache
 ---> 55934c8028d2
Step 9/24 : ENV BUNDLE_SILENCE_ROOT_WARNING=1                                                                                       	  PATH="$GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH"
 ---> Using cache
 ---> 2d9196f6d312
Step 10/24 : RUN amazon-linux-extras install corretto8                                                                                 && yum -y install maven                                                                                                 && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> e9c991046ee6
Step 11/24 : COPY m2-settings.xml /root/.m2/settings.xml
 ---> Using cache
 ---> d0f359f5b5d8
Step 12/24 : RUN amazon-linux-extras install docker                                                                                    && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> 7afd256db177
Step 13/24 : VOLUME /var/lib/docker
 ---> Using cache
 ---> e2810d0f4724
Step 14/24 : RUN yum -y install awscli git gzip openssl rsync tar unzip which zip                                                      && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> e3724e490d61
Step 15/24 : RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -                                                               && yum -y install nodejs                                                                                                && yum clean all && rm -rf /var/cache/yum                                                                               && npm set unsafe-perm true
 ---> Using cache
 ---> 0b35506ae233
Step 16/24 : RUN curl -sSL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo                                       && yum -y install yarn                                                                                                  && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> d8dcee6cf4d4
Step 17/24 : COPY ssh_config /root/.ssh/config
 ---> Using cache
 ---> 752e0f7de1da
Step 18/24 : COPY dockerd-entrypoint.sh /usr/local/bin/
 ---> Using cache
 ---> e176c33832e6
Step 19/24 : ENV CHARSET=UTF-8                                                                                                           LC_ALL=C.UTF-8
 ---> Using cache
 ---> 56ac18723120
Step 20/24 : ARG BUILD_TIMESTAMP
 ---> Using cache
 ---> 92b241d049f2
Step 21/24 : ARG COMMIT_ID
 ---> Using cache
 ---> 1c5f0093f03b
Step 22/24 : LABEL org.opencontainers.image.created=${BUILD_TIMESTAMP}                                                                     org.opencontainers.image.title="jsii/superchain"                                                                        org.opencontainers.image.description="An image to build cross-language artifacts with AWS jsii"                         org.opencontainers.image.url="https://github.com/aws/jsii/tree/master/superchain"                                       org.opencontainers.image.source="https://github.com/aws/jsii.git"                                                       org.opencontainers.image.revision=$COMMIT_ID
 ---> Using cache
 ---> 2257e28a1a29
Step 23/24 : RUN yum -y upgrade                                                                                                        && yum clean all && rm -rf /var/cache/yum
 ---> Using cache
 ---> 35ed30753c0d
Step 24/24 : CMD ["/bin/bash"]
 ---> Using cache
 ---> ddd141a3722f
Successfully built ddd141a3722f
Successfully tagged superchain:latest
jdavis@jdavis-Inspiron-ubuntu:~/repo/github/jsii$ docker run --rm --net=host -it -v $PWD:$PWD -w $PWD ${IMAGE}
bash-4.2# yarn install && yarn build
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-09fbffb3-d987-407b-88e6-d054282ad841 > jsii-runtime > wasm-loader@1.3.0" has unmet peer dependency "wasm-dce@1.x".
[4/4] Building fresh packages...
Done in 34.61s.
yarn run v1.19.1
$ lerna run build --stream --sort --concurrency=1
lerna notice cli v3.18.3
lerna info Executing command in 23 packages: "yarn run build"
codemaker: $ tsc --build && npm run lint
codemaker: > codemaker@0.20.1 lint /home/jdavis/repo/github/jsii/packages/codemaker
codemaker: > eslint . --ext .js,.ts --ignore-path=.gitignore
jsii-build-tools: $ chmod +x bin/*
jsii-dotnet-jsonmodel: $ tsc --build && /bin/bash ./build.sh
jsii-dotnet-jsonmodel: > jsii-dotnet-jsonmodel@0.20.1 gen /home/jdavis/repo/github/jsii/packages/jsii-dotnet-jsonmodel
jsii-dotnet-jsonmodel: > /bin/bash ./generate.sh
jsii-dotnet-jsonmodel: Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
jsii-dotnet-jsonmodel: Copyright (C) Microsoft Corporation. All rights reserved.
jsii-dotnet-jsonmodel:   Restore completed in 2.65 sec for /home/jdavis/repo/github/jsii/packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj.
jsii-dotnet-jsonmodel:   Restore completed in 6 sec for /home/jdavis/repo/github/jsii/packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel.UnitTests/Amazon.JSII.JsonModel.UnitTests.csproj.
jsii-dotnet-jsonmodel:   Restore completed in 10.21 sec for /home/jdavis/repo/github/jsii/packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel.UnitTests/Amazon.JSII.JsonModel.UnitTests.csproj.
jsii-dotnet-jsonmodel: Build FAILED.
jsii-dotnet-jsonmodel:     0 Warning(s)
jsii-dotnet-jsonmodel:     0 Error(s)
jsii-dotnet-jsonmodel: Time Elapsed 00:00:14.12
jsii-dotnet-jsonmodel: MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
jsii-dotnet-jsonmodel: Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:  ---> System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start()
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
jsii-dotnet-jsonmodel:    --- End of inner exception stack trace ---
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Int64 hostHandshake, Int64 clientHandshake, NodeContextTerminateDelegate terminateNode)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass67_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
jsii-dotnet-jsonmodel: --- End of stack trace from previous location where exception was thrown ---
jsii-dotnet-jsonmodel:    at Microsoft.Build.Execution.BuildManager.EndBuild()
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
jsii-dotnet-jsonmodel: MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
jsii-dotnet-jsonmodel: Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:  ---> System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start()
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
jsii-dotnet-jsonmodel:    --- End of inner exception stack trace ---
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
jsii-dotnet-jsonmodel: Unhandled exception. Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:  ---> System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start()
jsii-dotnet-jsonmodel:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
jsii-dotnet-jsonmodel:    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
jsii-dotnet-jsonmodel:    --- End of inner exception stack trace ---
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
jsii-dotnet-jsonmodel:    at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
jsii-dotnet-jsonmodel: error Command failed with exit code 134.
jsii-dotnet-jsonmodel: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 134 in 'jsii-dotnet-jsonmodel'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by RomainMuller** [comment]
The problem on your Ubuntu box might be the UID/GID that your Docker container runs with. On `macOS`, it'll typically run as the current user (so the `-v ${PWD}:${PWD}` mount will work super nicely).

On Ubuntu, it might run under a different user, and maybe this is causing file permission issues to cause trippy errors during the build?

A few things you might want to check:
- Are you running on a clean tree (your trace shows you switching branches, but I don't know if that is a fresh clone or not). If not, maybe try to `git clean -fqdX` before re-trying.
- Is the UID docker runs with allowed access to the files in your checkout

One thing you could maybe do is try to just start a container without the `-v` and `-w` options, and clone the repository within the container... This should get rid of any UID/GID and permission mismatches and hopefully narrows down the possibilities of what is going wrong!

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
