### ISSUE TITLE
ec2.Vpc.from_lookup return resource that does not implement IVpc

### ISSUE THREAD

**Issue by dxunix** [aws/jsii#990]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 
* **Platform:**    MacOS (Darwin ********** 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64)

### What is the problem?

Try to get a VPC object from the existing VPC through ec2.Vpc.from_lookup() by vpc_id.  However, the returned object does not have the attributes described in the document.
 ```python       
        vpc = ec2.Vpc.from_lookup(self, "myvpc", vpc_id=VPC_ID)
        # _vpc = ec2.Vpc.from_lookup(self, "myvpc", is_default=True)
        print("vpc is {}".format(vpc.vpc_id))
```

### Verbose Log
```
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    EcsTestStack(app, 'ecs-test-stack', env={'account': '************', 'region': 'us-east-1'})
  File "/Users/dye/dev/cdk/service-chk/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/dye/dev/cdk/service-chk/ecstest/ecstest_stacks.py", line 28, in __init__
    print("vpc is {}".format(vpc.vpc_id))
AttributeError: 'Resource' object has no attribute 'vpc_id'
```

**Comment by dxunix** [comment]
solved after upgraded to  1.16.3
